import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,ENTRY} from '../src/game.js';
import {ROOMS,CAST,LEVELS} from '../src/content.js';
import {strings} from '../src/i18n.js';
function tick(g,seconds){for(let i=0;i<seconds*20;i++){if(g.event){const e=g.event;g.resolveEvent(e==='coffee'||e==='review'?1:0);}g.update(.05);}}
function expand(g){g.addRoom('toilet',{x:1,y:11,w:3,h:3});if(g.level>=2||g.mode==='sandbox'){assert.ok(g.addRoom('therapy',{x:5,y:11,w:4,h:4}).room);g.hire('park');}if(g.level>=3||g.mode==='sandbox'){assert.ok(g.addRoom('surgery',{x:16,y:11,w:5,h:4}).room);g.hire('nia');}}

test('patients complete diagnosis, receive their correct treatment and produce actual income',()=>{const g=new Game({seed:42});g.nextEvent=99999;g.arrivalTimer=99999;g.patients=g.patients.slice(0,1);const start=g.cash;tick(g,100);assert.equal(g.patients.length,0);assert.equal(g.cured+g.failed,1);assert.equal(g.income,g.cured?610:90);assert.equal(g.cash,start+g.income-g.expenses);assert.ok(g.rooms.every(r=>r.patientId===null));});
test('placement rejects collisions, too-small footprints, doorway blockage and locked departments',()=>{const g=new Game({seed:42});assert.equal(g.placement('gp',{x:2,y:2,w:3,h:3}),'invalidRoom');assert.equal(g.placement('gp',{x:2,y:11,w:2,h:3}),'smallRoom');assert.equal(g.placement('surgery',{x:2,y:11,w:4,h:4}),'invalidRoom');assert.equal(g.placement('gp',{x:3,y:6,w:3,h:3}),'badPlacement');assert.ok(g.path(ENTRY,g.door(g.rooms[0])).length);const result=g.addRoom('gp',{x:2,y:11,w:4,h:4});assert.ok(result.room);assert.ok(g.path(ENTRY,g.door(result.room)));});
test('ledger reconciles hiring, building, upgrading, demolition, events and daily bills',()=>{const g=new Game({seed:21});const initial=g.cash;const r=g.addRoom('toilet',{x:1,y:11,w:3,h:3}).room;g.upgrade(r.id);g.sell(r.id);g.hire('park');g.event='grant';g.resolveEvent(0);tick(g,200);assert.ok(Math.abs(g.cash-(initial+g.income-g.expenses-g.construction))<.001);});
test('events always allow free responses and donations while the balance is negative',()=>{for(const [event,index,expected] of [['coffee',1,-100],['review',1,-100],['grant',0,800],['rush',0,500]]){const g=new Game({seed:1});g.cash=-100;g.event=event;assert.equal(g.resolveEvent(index).error,undefined);assert.equal(g.event,null);assert.equal(g.cash,expected);const clock=g.clock;g.update(.05);assert.ok(g.clock>clock);}});
test('all campaigns can be won with sensible staffing, correct departments and no cheating',()=>{for(const level of [1,2,3]){const g=new Game({seed:42,level});expand(g);for(let i=0;i<16000&&!g.won&&!g.over;i++){if(g.event)g.resolveEvent(g.event==='coffee'||g.event==='review'?1:0);g.update(.05);}assert.ok(g.won,`Episode ${level}, cures=${g.cured}, reputation=${g.rep}`);assert.ok(g.cured>=LEVELS[level-1].goal);assert.ok(g.rep>=LEVELS[level-1].rep);assert.ok(g.cash>0);}});
test('sandbox has all departments and never fires a campaign win',()=>{const g=new Game({mode:'sandbox',seed:3});assert.equal(g.cash,35000);assert.ok(g.available('surgery'));expand(g);tick(g,600);assert.equal(g.won,false);assert.ok(g.cured>10);});
test('support upgrades improve actual recovery, comfort and research progress',()=>{const make=()=>{const g=new Game({seed:9});g.nextEvent=99999;g.arrivalTimer=99999;g.patients=[];return g;};let a=make(),b=Game.restore(a.snapshot());for(const g of [a,b]){g.staff[0].resting=true;g.staff[0].fatigue=85;}b.upgrade(b.rooms.find(r=>r.type==='lounge').id);tick(a,10);tick(b,10);assert.ok(b.staff[0].fatigue<a.staff[0].fatigue);
 a=make();a.addRoom('toilet',{x:1,y:11,w:3,h:3});const p=a.spawnPatient('daydream');p.stage='treatment';b=Game.restore(a.snapshot());b.upgrade(b.rooms.find(r=>r.type==='toilet').id);tick(a,20);tick(b,20);assert.ok(b.patients[0].patience>a.patients[0].patience);
 a=make();a.addRoom('lab',{x:1,y:11,w:3,h:3});a.hire('park');a.startResearch('care');b=Game.restore(a.snapshot());b.upgrade(b.rooms.find(r=>r.type==='lab').id);tick(a,20);tick(b,20);assert.ok(b.project.progress>a.project.progress);});
test('save restoration continues deterministically and preserves future simulation',()=>{const a=new Game({seed:45,level:3});expand(a);tick(a,125);const b=Game.restore(a.snapshot());tick(a,240);tick(b,240);assert.deepEqual(a.snapshot(),b.snapshot());});
test('untrusted imported saves cannot override engine methods or carry broken entity links',()=>{const good=new Game({seed:1}).snapshot();assert.equal(typeof Game.restore({...good,update:null}).update,'function');for(const mutation of [s=>s.id=0,s=>s.rooms[0].patientId=9999,s=>s.staff[0].roomId=9999,s=>s.patients[0].targetRoom=9999,s=>s.cash='1000',s=>s.rooms[0].x=-5,s=>s.patients[0].path=[{x:null,y:3}]]){const s=structuredClone(good);mutation(s);assert.throws(()=>Game.restore(s));}});
test('staff and rooms cannot disappear under a patient in active treatment',()=>{const g=new Game({seed:10});g.nextEvent=99999;for(let i=0;i<300;i++)g.update(.05);const busy=g.rooms.find(r=>r.patientId);assert.ok(busy);assert.equal(g.sell(busy.id).error,'removeBusy');assert.equal(g.dismiss(busy.staffId).error,'removeBusy');});
test('zero delta pauses all simulation and a pending event freezes billing',()=>{const g=new Game({seed:1});const before=g.snapshot();g.update(0);assert.deepEqual(g.snapshot(),before);g.event='coffee';const withEvent=g.snapshot();g.update(.25);assert.deepEqual(g.snapshot(),withEvent);});
test('English and German have complete matching interface dictionaries',()=>{assert.deepEqual(Object.keys(strings.en).sort(),Object.keys(strings.de).sort());for(const dictionary of Object.values(strings))for(const value of Object.values(dictionary))assert.ok(value.length>0);});
