import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,ENTRY} from '../src/game.js';
import {ROOMS,LEVELS,EVENTS} from '../src/content.js';
import {GUIDE,YEAR_SECONDS} from '../src/tutorial.js';
import {strings} from '../src/i18n.js';
function resolve(g){if(!g.event)return;const ev=EVENTS.find(e=>e.id===g.event);const choice=ev.choices.findIndex(c=>c.cost===0&&c.effect!=='mafiaLoan');g.resolveEvent(choice>=0?choice:0);}
function tick(g,seconds,guide=false){for(let i=0;i<Math.round(seconds*20);i++){resolve(g);if(guide)follow(g);g.update(.05);}}
function base(g){for(const step of GUIDE.slice(0,6)){if(step.room)assert.ok(g.addRoom(step.room,step.rect).room);else if(step.cast)assert.ok(g.hire(step.cast).staff);}assert.equal(g.openClinic().error,undefined);}
function follow(g){const step=g.guide();if(!step)return;if(step.room)assert.ok(g.addRoom(step.room,step.rect).room);else if(step.cast)g.hire(step.cast);else if(step.id==='open')g.openClinic();else if(step.id==='chart')g.readChart(g.records[0].id);else if(step.upgrade)g.upgrade(g.rooms.find(r=>r.type===step.upgrade).id);}
function support(g){for(const id of ['lounge','toilet']){const s=GUIDE.find(s=>s.id===id);g.addRoom(s.room,s.rect);}g.hire('otto');}
function specialty(g){if(g.level>=2||g.mode==='sandbox'){assert.ok(g.addRoom('therapy',{x:6,y:11,w:4,h:4}).room);g.hire('park');}if(g.level>=3||g.mode==='sandbox'){assert.ok(g.addRoom('surgery',{x:17,y:7,w:5,h:3}).room);g.hire('nia');}if(g.level>=2){assert.ok(g.addRoom('lab',{x:10,y:11,w:3,h:3}).room);g.hire('park');g.startResearch(LEVELS[g.level-1].project);}}

test('every new hospital starts empty with $50,000 and no earned profit',()=>{for(const mode of ['tutorial','campaign','sandbox']){const g=new Game({mode,seed:1});assert.equal(g.cash,50000);assert.equal(g.rooms.length+g.staff.length+g.patients.length+g.records.length,0);assert.equal(g.yearlyProfit(),0);assert.equal(g.admissionsOpen,false);tick(g,100);assert.equal(g.clock,0);assert.equal(g.calendar,0);}});
test('guided setup follows actual state and cannot open with an unstaffed clinic',()=>{const g=new Game({seed:1});assert.equal(g.guide().id,'reception');assert.equal(g.openClinic().error,'openingRequirements');const step=g.guide();g.addRoom(step.room,step.rect);assert.equal(g.guide().id,'receptionist');g.hire('milo');assert.equal(g.guide().id,'receptionist');g.hire('rosa');assert.equal(g.guide().id,'diagnosis');assert.equal(g.openClinic().error,'openingRequirements');});
test('patients must complete a staffed reception before any diagnosis or income',()=>{const g=new Game({seed:42});base(g);g.dismiss(g.staff.find(s=>s.role==='receptionist').id);tick(g,80);assert.equal(g.income,0);assert.ok(g.patients.every(p=>p.stage==='reception'));g.hire('rosa');tick(g,100);assert.ok(g.income>0);for(const r of g.records){const steps=r.timeline.map(e=>e.code);if(steps.includes('diagnosed'))assert.ok(steps.indexOf('registered')<steps.indexOf('diagnosed'));}});
test('all patients retain individual charts, identity, charge items and complete journeys after discharge',()=>{const g=new Game({seed:42});base(g);support(g);tick(g,200);assert.ok(g.records.length>g.patients.length);assert.equal(new Set(g.records.map(r=>r.number)).size,g.records.length);for(const r of g.records){assert.ok(r.name&&r.birthDate&&r.number);assert.equal(r.bill,r.diagnosisCharge+r.treatmentCharge);if(r.dischargedAt!==null){assert.ok(['cured','failed','left'].includes(r.outcome));assert.equal(r.timeline.at(-1).code,'discharged');assert.ok(r.dischargedAt>=r.admittedAt);}}const restored=Game.restore(g.snapshot());assert.deepEqual(restored.records,g.records);});
test('unhappy patients have archived charts too',()=>{const g=new Game({seed:1});base(g);g.arrivalTimer=99999;const p=g.spawnPatient('jitters');p.patience=.001;tick(g,1);assert.equal(g.record(p.id).outcome,'left');assert.notEqual(g.record(p.id).dischargedAt,null);});
test('starting capital and building purchases are correctly excluded/deducted from profit',()=>{const g=new Game({seed:1});g.addRoom('reception',GUIDE[0].rect);assert.equal(g.yearlyProfit(),-ROOMS.reception.cost);assert.equal(g.cash,50000+g.yearlyProfit());baseWithoutReception(g);tick(g,120);assert.equal(g.cash,50000+g.income-g.expenses-g.construction+g.financing);});
function baseWithoutReception(g){g.hire('rosa');for(const s of GUIDE.slice(2,6)){if(s.room)g.addRoom(s.room,s.rect);if(s.cast)g.hire(s.cast);}g.openClinic();}
test('the tutorial requires a closed year and all lessons, never a projected profit figure',()=>{const g=new Game({seed:42});base(g);support(g);for(let i=0;i<7199;i++){resolve(g);follow(g);g.update(.05);}assert.equal(g.won,false);assert.equal(g.financialYears.length,0);resolve(g);g.update(.05);assert.equal(g.financialYears.length,1);assert.ok(g.financialYears[0].profit>=100000);assert.equal(g.won,true);assert.equal(g.month,1);assert.equal(g.year,2);assert.equal(g.yearlyProfit(),0);});
test('earning the money cannot bypass chart reading and other tutorial lessons',()=>{const g=new Game({seed:42});base(g);tick(g,360);assert.equal(g.won,false);assert.ok(g.financialYears[0].profit>=100000);g.readChart(g.records[0].id);support(g);g.upgrade(g.rooms.find(r=>r.type==='gp').id);g.upgrade(g.rooms.find(r=>r.type==='pharmacy').id);assert.equal(g.won,true);});
test('guided tutorial wins within a real completed six-minute year across eight seeds',()=>{for(const seed of [1,2,3,7,42,99,123,2026]){const g=new Game({seed});while(!g.admissionsOpen)follow(g);tick(g,YEAR_SECONDS,true);assert.ok(g.won,`seed ${seed}, profit ${g.financialYears[0]?.profit}`);assert.equal(g.financialYears.length,1);assert.ok(g.financialYears[0].profit>=100000);assert.equal(g.cash,50000+g.income-g.expenses-g.construction+g.financing);}});
test('December bills are charged exactly once before annual close',()=>{const g=new Game({seed:1});base(g);g.arrivalTimer=99999;g.nextEvent=99999;g.patients=[];const setup=g.construction,cost=g.dailyCost();tick(g,360);assert.equal(g.financialYears[0].expenses,cost*12);assert.equal(g.financialYears[0].profit,-setup-cost*12);assert.equal(g.yearlyProfit(),0);tick(g,.05);assert.equal(g.financialYears.length,1);});
test('mafia credit affects cash and repayments, never inflates earned annual profit',()=>{const g=new Game({seed:2});base(g);g.arrivalTimer=99999;g.event='mafia';const cash=g.cash,profit=g.yearlyProfit();g.resolveEvent(0);assert.equal(g.cash,cash+12000);assert.equal(g.yearlyProfit(),profit);assert.equal(g.debtRemaining(),18000);tick(g,30);assert.equal(g.debtRemaining(),15750);assert.equal(g.financing,10500);assert.equal(g.yearlyProfit(),profit-g.dailyCost()-750);assert.equal(g.cash,50000+g.income-g.expenses-g.construction+g.financing);});
test('free event responses remain usable in debt and modifiers expire',()=>{const g=new Game({seed:1});base(g);g.cash=-1;g.event='printer';assert.equal(g.resolveEvent(1).error,undefined);assert.equal(g.modifiers.length,1);tick(g,60.1);assert.equal(g.modifiers.length,0);g.event='mafia';assert.equal(g.resolveEvent(1).error,undefined);assert.equal(g.contracts.length,0);});
test('room access, occupied-room safety and construction collisions remain enforced',()=>{const g=new Game({seed:10});base(g);assert.equal(g.placement('gp',{x:2,y:2,w:3,h:3}),'invalidRoom');assert.equal(g.placement('gp',{x:2,y:11,w:2,h:3}),'smallRoom');assert.equal(g.placement('gp',{x:3,y:6,w:3,h:3}),'badPlacement');for(let i=0;i<500&&!g.rooms.some(r=>r.patientId);i++)g.update(.05);const busy=g.rooms.find(r=>r.patientId);assert.ok(busy);assert.equal(g.sell(busy.id).error,'removeBusy');assert.equal(g.dismiss(busy.staffId).error,'removeBusy');assert.ok(g.path(ENTRY,g.door(g.rooms[0])));});
test('story requires specialist treatments and research, free play has no forced win',()=>{const g=new Game({mode:'campaign',level:3,seed:1});g.cured=100;g.rep=100;assert.equal(g.storyGoalsMet(),false);g.curedByRoom.surgery=18;assert.equal(g.storyGoalsMet(),false);g.completed.push('speed');assert.equal(g.storyGoalsMet(),true);const sandbox=new Game({mode:'sandbox',seed:3});base(sandbox);support(sandbox);specialty(sandbox);tick(sandbox,400);assert.equal(sandbox.won,false);assert.ok(sandbox.cured>0);});
test('all story scenarios remain achievable with appropriate specialty staffing',()=>{for(const level of [1,2,3]){const g=new Game({mode:'campaign',level,seed:42});base(g);support(g);specialty(g);g.upgrade(g.rooms.find(r=>r.type==='gp').id);g.upgrade(g.rooms.find(r=>r.type==='pharmacy').id);for(let i=0;i<50000&&!g.won&&!g.over;i++){resolve(g);g.update(.05);}assert.ok(g.won,`level ${level}, ${g.cured} cures, ${JSON.stringify(g.curedByRoom)}, cash ${g.cash}`);}});
test('save restoration is deterministic during reception, service, and across year-end',()=>{for(const checkpoint of [3,30,127,359.95,360.05]){const a=new Game({seed:42});base(a);support(a);tick(a,checkpoint);const b=Game.restore(a.snapshot());tick(a,45);tick(b,45);assert.deepEqual(a.snapshot(),b.snapshot());}});
test('malformed imports cannot forge calendars, annual baselines or chart identity',()=>{const g=new Game({seed:1});base(g);tick(g,20);const good=g.snapshot();for(const mutate of [s=>s.day=10000,s=>s.yearStart.income=-1000000,s=>s.patientSerial=0,s=>s.records[1].number=s.records[0].number,s=>s.records[0].id=s.rooms[0].id,s=>s.records[0].birthDate={},s=>s.records[0].outcome={},s=>s.records[0].priority='<b>html</b>',s=>s.records[0].timeline[0].roomType='<b>html</b>',s=>s.records[0].timeline[0].year='<b>html</b>',s=>s.ledger=[{year:'<b>html</b>',day:1,cost:5}],s=>s.contracts=[{months:8}],s=>s.curedByRoom={surgery:99999},s=>s.records[0].illness='funny',s=>s.rooms[0].patientId=99999]){const data=structuredClone(good);mutate(data);assert.throws(()=>Game.restore(data));}assert.equal(typeof Game.restore({...good,update:null}).update,'function');});
test('v1 hospitals migrate without losing their money, rooms or active patients',()=>{const current=new Game({mode:'campaign',seed:1});base(current);tick(current,10);const old=current.snapshot();old.version=1;old.patients.forEach(p=>p.stage='diagnosis');old.rooms.forEach(r=>r.patientId=null);old.patients.forEach(p=>{p.state='waiting';p.targetRoom=null;});const migrated=Game.restore(old);assert.equal(migrated.version,2);assert.equal(migrated.cash,old.cash);assert.equal(migrated.rooms.length,old.rooms.length);assert.equal(migrated.records.length,old.patients.length);assert.equal(migrated.yearlyProfit(),0);});
test('English and German provide the same complete interface keys',()=>{assert.deepEqual(Object.keys(strings.en).sort(),Object.keys(strings.de).sort());for(const dictionary of Object.values(strings))for(const value of Object.values(dictionary))assert.ok(value.length>0);});
