import {ROOMS} from './content.js';
import {ENTRY} from './game.js';
import {EXPANSIONS,gridFor} from './expansion.js';
import {roomUpgradeInfo} from './upgrade-info.js';

export function renderRoomTransform(game,room,helpers){
 const {copy,btn,money}=helpers,disabled=game.over||game.event||room.renovating;
 return `<section class="room-transform-options"><h3>${copy('Change the room shell','Raumhülle verändern')}</h3><p>${copy('Furniture keeps its position inside the room. People leave safely before work begins.','Möbel behalten ihre Position im Raum. Vor dem Umbau verlassen alle sicher den Raum.')}</p><small>${copy('Extra floor','Zusätzlicher Boden')}: ${money(Math.ceil(ROOMS[room.type].cost/9))} / ${copy('tile','Feld')} · ${copy('Relocation','Umzug')}: ${money(Math.ceil(ROOMS[room.type].cost*.15))}. ${copy('Shrinking gives no refund.','Verkleinern bringt keine Erstattung.')}</small>${room.renovating?`<p>${copy('Finishing visits and clearing the room…','Besuche werden beendet und der Raum wird frei…')}</p>`:''}<div class="room-transform-buttons">${[['resize',copy('Resize room','Raumgröße ändern')],['move',copy('Move room','Raum verschieben')]].map(([mode,title])=>btn('room-transform',title,'secondary full',`data-id="${room.id}" data-mode="${mode}" ${disabled?'disabled':''}`)).join('')}</div></section>`;
}

export function renderRoomUpgrade(game,room,helpers){
 const {copy,label,money,btn,escape}=helpers,info=roomUpgradeInfo(game,room),value=text=>escape(copy(text,String(text).replace(/(\d)\.(\d)/g,'$1,$2')));
 if(info.atMax)return `<div class="upgrade-complete">✓ ${copy('Level 3 · fully upgraded','Stufe 3 · vollständig verbessert')}</div>`;
 return `<section class="room-upgrade"><div class="upgrade-heading"><b>${copy('Upgrade','Verbesserung')}</b><span>${copy('Level','Stufe')} ${info.currentLevel} → ${info.nextLevel}</span></div><dl class="upgrade-effects">${info.effects.map(effect=>`<div><dt>${escape(label(effect.label))}</dt><dd><span>${value(effect.before)}</span> → <b>${value(effect.after)}</b></dd></div>`).join('')}</dl>${info.note?`<details class="upgrade-explanation"><summary>${copy('How this works','So wirkt die Verbesserung')}</summary><p>${escape(label(info.note))}</p></details>`:''}<p class="upgrade-upkeep">${copy('Additional upkeep','Zusätzlicher Unterhalt')}: <b>+${money(info.monthlyIncrease)} / ${copy('month','Monat')}</b></p>${info.draft?`<p class="development-note">${copy('Effects start when furnishing is finished.','Die Wirkung beginnt, sobald der Raum fertig eingerichtet ist.')}</p>`:''}${btn('upgrade',`${copy('Upgrade to level','Auf Stufe')} ${info.nextLevel} ${copy('','verbessern')} · ${money(info.cost)}`,'primary full',`data-id="${room.id}" ${info.affordable?'':'disabled'}`)}${!info.affordable?`<p class="development-shortfall">${copy('Still needed','Es fehlen noch')}: ${money(info.cost-game.cash)}</p>`:''}</section>`;
}

function plan(game,preview,helpers){
 const {copy,escape}=helpers,owned=game.expansions||[],grid=game.grid,chosen=EXPANSIONS.find(e=>e.id===preview&&!owned.includes(e.id)),next=chosen?gridFor([...owned,chosen.id]):grid;
 const entry={x:15+ENTRY.x*7,y:20+ENTRY.y*7};
 const area=(x,y,w,h,cls)=>`<rect x="${15+x*7}" y="${20+y*7}" width="${w*7}" height="${h*7}" class="${cls}"/>`;
 return `<svg class="development-plan" viewBox="0 0 240 208" role="img" aria-label="${escape(copy('Clinic plan: solid green is owned; the highlighted wing is the selected extension.','Klinikplan: Grün gehört dir; der markierte Flügel ist der ausgewählte Ausbau.'))}"><defs><pattern id="development-hatch" width="7" height="7" patternUnits="userSpaceOnUse"><path d="M0 7 7 0" stroke="#b99c68" stroke-width="1"/></pattern></defs>${area(0,0,30,24,'plan-available')}${area(0,0,grid.w,grid.h,'plan-owned')}${chosen?area(chosen.id==='east'?grid.w:0,chosen.id==='south'?grid.h:0,chosen.id==='east'?next.w-grid.w:next.w,chosen.id==='south'?next.h-grid.h:next.h,'plan-preview'):''}${game.rooms.map(r=>area(r.x,r.y,r.w,r.h,'plan-room')).join('')}<text x="99" y="79" class="plan-label">${grid.w} × ${grid.h}</text><text x="204" y="87" class="plan-direction">${copy('E','O')}</text><text x="99" y="173" class="plan-direction">S</text><circle cx="${entry.x}" cy="${entry.y}" r="4" fill="#fffbed" stroke="#416854" stroke-width="2"/><text x="${entry.x+8}" y="${entry.y+4}" class="plan-entry">${copy('Entrance','Eingang')}</text></svg>`;
}

export function renderDevelopmentPanel(game,{view='land',preview=null,helpers}){
 const {copy,label,btn,money,escape,panelHeader}=helpers,land=view!=='upgrades',owned=game.expansions||[];
 const tabs=`<nav class="staff-view-tabs" aria-label="${copy('Development views','Ausbauansichten')}">${[['land',copy('Clinic space','Klinikfläche')],['upgrades',copy('Room upgrades','Raum-Upgrades')]].map(([id,title])=>btn('development-view',title,`staff-view-button${(land?id==='land':id==='upgrades')?' active':''}`,`data-view="${id}" aria-pressed="${land?id==='land':id==='upgrades'}"`)).join('')}</nav>`;
 const content=land?`<p class="panel-intro">${copy('More room for your ideas. And the queue that insists it has an appointment.','Mehr Platz für deine Ideen. Und die Schlange, die angeblich nur kurz etwas fragen will.')}</p>${plan(game,preview,helpers)}<div class="development-balance"><span>${copy('Available funds','Verfügbares Geld')}</span><b>${money(game.cash)}</b></div>${EXPANSIONS.map(e=>{
  const bought=owned.includes(e.id),next=bought?game.grid:gridFor([...owned,e.id]),tiles=next.w*next.h-game.grid.w*game.grid.h,affordable=game.cash>=e.cost;
  return `<article class="expansion-card${preview===e.id&&!bought?' selected':''}"><div class="expansion-heading"><span class="expansion-symbol" aria-hidden="true">${e.id==='east'?'→':'↓'}</span><div><h3>${escape(label(e.name))}</h3><small>${bought?copy('Part of your clinic','Gehört zu deiner Klinik'):e.id==='east'?copy('6 tiles wider','6 Felder breiter'):copy('6 tiles deeper','6 Felder tiefer')}</small></div></div>${bought?`<p class="upgrade-complete">✓ ${copy('Built · ready to furnish','Ausgebaut · bereit zum Einrichten')}</p>`:`<p>${copy('Adds','Bringt')} <b>${tiles} ${copy('floor tiles','Bodenfelder')}</b>. ${copy('Keep the perimeter clear for corridors.','Halte den Rand als Flur frei.')}</p>${btn('expansion-preview',preview===e.id?copy('Shown on the plan','Im Plan markiert'):copy('Show on plan','Auf Plan zeigen'),'text-button',`data-expansion="${e.id}" aria-pressed="${preview===e.id}"`)}${btn('expand-clinic',`${copy('Build wing','Flügel anbauen')} · ${money(e.cost)}`,'primary full',`data-expansion="${e.id}" ${affordable&&!game.over&&!game.event?'':'disabled'}`)}<small class="${affordable?'development-after':'development-shortfall'}">${affordable?copy('Balance afterwards','Kontostand danach')+': '+money(game.cash-e.cost):copy('Still needed','Es fehlen noch')+': '+money(e.cost-game.cash)}</small>`}</article>`;
 }).join('')}<p class="development-note">${copy('One-time construction costs count towards annual profit. New space is empty: place rooms, furniture and staff yourself. Rooms and their upkeep are paid separately.','Einmalige Baukosten zählen beim Jahresgewinn mit. Die neue Fläche ist leer: Räume, Möbel und Personal platzierst du selbst. Räume und ihr Unterhalt kosten zusätzlich.')}</p>${owned.length?btn('development-build',copy('Build on the new space','Neue Fläche bebauen'),'secondary full'):''}`:
 `<p class="panel-intro">${copy('Better equipment or more comfort: compare the real effect before spending. Each room has three levels.','Bessere Geräte oder mehr Komfort: Vergleiche die Wirkung vor dem Kauf. Jeder Raum hat drei Stufen.')}</p>${game.rooms.length?game.rooms.map(r=>`<article class="development-room"><div class="development-room-heading"><span style="background:${ROOMS[r.type].color}" aria-hidden="true">${ROOMS[r.type].icon}</span><div><h3>${escape(label(ROOMS[r.type].name))}</h3><small>${copy('Room','Raum')} ${r.id} · ${r.w} × ${r.h}</small></div>${btn('room','↗','icon-btn',`data-id="${r.id}" aria-label="${escape(copy('Show room','Raum ansehen')+' '+r.id)}"`)}</div>${renderRoomUpgrade(game,r,helpers)}${renderRoomTransform(game,r,helpers)}</article>`).join(''):`<div class="staff-empty"><h3>${copy('Your first room comes first','Erst kommt dein erster Raum')}</h3><p>${copy('Build and furnish a room. Its upgrades will appear here.','Baue einen Raum und richte ihn ein. Seine Verbesserungen findest du dann hier.')}</p>${btn('development-build',copy('Open build menu','Baumenü öffnen'),'primary full')}</div>`}`;
 return panelHeader(copy('Grow your clinic','Deine Klinik wächst'),copy('EXPANSION & UPGRADES','AUSBAU & VERBESSERUNGEN'))+tabs+`<div class="panel-scroll development-content">${content}</div>`;
}
