import {patchHTML} from './dom.js';
import {Announcer} from './voice.js';
import {roomObjects,findObject,OBJECT_INFO} from './objects.js';
import {CharacterModel,appearanceFor,portraitSeed} from './characters.js';
import {Game} from './game.js';
import {Renderer} from './renderer.js';
import {ROOMS,CAST,ILLNESSES,LEVELS,PROJECTS,EVENTS,PATIENT_FACTS,COMPLAINTS,tr} from './content.js';
import {ROLES,PERSONALITIES,RECRUITMENT_FEE} from './recruitment.js';
import {GUIDE,YEAR_SECONDS,ANNUAL_TARGET} from './tutorial.js';
import {translator,detectLanguage} from './i18n.js';
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let prefs={},progress=[];try{prefs=JSON.parse(localStorage.getItem('scrubssitel-prefs')||'{}');progress=JSON.parse(localStorage.getItem('scrubssitel-progress')||'[]');if(!Array.isArray(progress))progress=[];}catch{}
let lang=['en','de'].includes(prefs.lang)?prefs.lang:detectLanguage(),t=translator(lang),game=new Game(),startScreen=true,savedGame=null,savedSource=null,paused=false,speed=1,panel=null,selected=null,modal=null,buildType=null,winShown=false,overShown=false,confirmAction=null,lastSave=0,autosaveEnabled=false,audio=null,patientFilter='active',recruitRole='receptionist',buildOpen=false;
const voice=new Announcer({onStatus(){if(renderer)renderUI();}});
function readStoredClinic(){savedGame=null;savedSource=null;try{savedSource=localStorage.getItem('scrubssitel-save');if(savedSource)savedGame=Game.restore(JSON.parse(savedSource));}catch{}}
readStoredClinic();
voice.reset(0);
const copy=(en,de)=>lang==='de'?de:en;
const portraitCache=new Map();
function patientPortrait(record){if(record.age>=16)return `./public/assets/sprites/patient-${record.variant}-0.png`;if(!portraitCache.has(record.variant)){const canvas=document.createElement('canvas');canvas.width=100;canvas.height=130;new CharacterModel(canvas.getContext('2d')).draw({id:record.variant,variant:record.variant,child:true,state:'idle'},{time:1,yaw:0,phase:0,walk:0,sit:0,work:0,celebrate:0},{x:50,y:122},135);portraitCache.set(record.variant,canvas.toDataURL());}return portraitCache.get(record.variant);}
function callText(call){return `${call.name}, ${copy('please come to','bitte zur')} ${label(ROOMS[call.roomType].name)}. ${copy('Room','Raum')} ${call.roomId}.`;}

const money=n=>new Intl.NumberFormat(lang==='de'?'de-DE':'en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const label=v=>tr(v,lang);
const icons={build:'▦',staff:'♟',research:'⚗',finances:'↗',patients:'▤',help:'?',settings:'⚙',pause:'Ⅱ',play:'▶',save:'↓',home:'⌂',close:'×'};
function btn(action,text,cls='',extra=''){return `<button type="button" class="${cls}" data-action="${action}" ${extra}>${text}</button>`;}
function iconBtn(action,icon,title){return btn(action,icon,'icon-btn',`title="${escape(title)}" aria-label="${escape(title)}"`);}
function staffPortrait(s){const key='staff:'+appearanceFor(s).key;if(!portraitCache.has(key)){const canvas=document.createElement('canvas');canvas.width=180;canvas.height=210;const ctx=canvas.getContext('2d');ctx.fillStyle='#edf1e5';ctx.fillRect(0,0,180,210);new CharacterModel(ctx).draw({...s,applicantId:s.applicantId||(typeof s.id==='string'?s.id:undefined),id:portraitSeed(s),state:'idle'},{time:1,yaw:Math.PI/4,phase:0,walk:0,sit:0,work:0,celebrate:0},{x:90,y:350},260);portraitCache.set(key,canvas.toDataURL());}return portraitCache.get(key);}
function staffStatus(s){return copy(({travelWork:'Walking to work',travelBreak:'On the way to a break',break:s.breakRoomId?'Break in the lounge':'Standing break',cleaning:'Cleaning',idle:'Waiting for a workplace'})[s.state]||(s.breakPending?'Finishing before break':'At work'),({travelWork:'Auf dem Weg zur Arbeit',travelBreak:'Auf dem Weg zur Pause',break:s.breakRoomId?'Pause im Personalraum':'Stehpause',cleaning:'Reinigt die Klinik',idle:'Wartet auf Arbeitsplatz'})[s.state]||(s.breakPending?'Beendet Behandlung vor Pause':'Am Arbeitsplatz'));}
function avatar(s,size=''){return `<span class="avatar model-avatar ${size}"><img src="${staffPortrait(s)}" alt="${escape(s.name)}"/></span>`;}

function persistPrefs(){try{localStorage.setItem('scrubssitel-prefs',JSON.stringify(prefs));}catch{}}
function chime(type='tap'){if(!prefs.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime;for(let i=0;i<(type==='cure'?3:1);i++){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=(type==='error'?180:type==='cure'?523:440)*[1,1.25,1.5][i];g.gain.setValueAtTime(.045,now+i*.08);g.gain.exponentialRampToValueAtTime(.001,now+.14+i*.08);o.connect(g);g.connect(audio.destination);o.start(now+i*.08);o.stop(now+.16+i*.08);}}catch{}}
function notify(text,error=false){const el=$('#toast');el.textContent=text;el.classList.toggle('error',error);el.classList.add('visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.classList.remove('visible'),3200);chime(error?'error':'tap');}
function result(r,success){if(r?.error){notify(t(r.error),true);return false;}if(success)notify(success);renderUI();return true;}
function save(show=true){if(startScreen)return false;try{localStorage.setItem('scrubssitel-save',JSON.stringify(game.snapshot()));localStorage.setItem('scrubssitel-progress',JSON.stringify(progress));if(show)notify(t('saved'));return true;}catch{if(show)notify(t('saveFailed'),true);return false;}}
function currentLevel(){return LEVELS[game.level-1];}
function shell(){document.documentElement.lang=lang;document.title=`Scrubssitel · ${t('brandSub')}`;
 $('#app').innerHTML=`<header class="topbar"><a class="brand" href="#" aria-label="Scrubssitel"><span class="brand-mark">✚</span><span><strong>Scrubssitel<span class="brand-dot">.</span></strong><small>${t('brandSub')}</small></span></a><div class="vital-stats" id="vitals"></div><div class="top-actions">${iconBtn('save','↓',t('save'))}${iconBtn('help','?',t('help'))}${iconBtn('settings','⚙',t('settings'))}<button class="language-button" data-action="switch-language" aria-label="${t('language')}">${lang.toUpperCase()}</button></div></header>
 <nav class="workbar" aria-label="${t('yourHospital')}"><button class="hospital-name" data-action="episodes"><span class="hospital-icon">⌂</span><span><b>${lang==='de'?'Klinik Miteinander':'Common Ground Hospital'}</b><small id="episode-label"></small></span><span class="chevron">⌄</span></button><div class="management-tabs">${btn('panel',`<span>🎟</span> ${copy('Queue','Warteliste')}`,'tab',`data-panel="queue" title="${copy('Waiting list','Warteliste')}" aria-label="${copy('Waiting list','Warteliste')}"`)}${['patients','staff','research','finances'].map(x=>btn('panel',`<span>${icons[x]}</span> ${t(x)}`,'tab',`data-panel="${x}" title="${t(x)}" aria-label="${t(x)}"`)).join('')}</div><div class="time-controls" id="time-controls"></div></nav>
 <main class="game-shell"><aside class="shift-sidebar" id="sidebar"></aside><section class="hospital-stage" aria-label="${t('floor')}"><div class="stage-topline"><span class="live-dot"></span><span id="stage-status">${t('planning')}</span><button class="clinic-open-button" data-action="open-clinic" id="clinic-open">${t('openClinic')} →</button><button class="voice-control" data-action="voice" id="voice-control"></button></div><canvas id="hospital-canvas" tabindex="0" aria-label="${t('floor')}. ${t('buildHint')}"></canvas><div class="view-controls">${iconBtn('zoom-out','−',t('zoomOut'))}<span id="zoom-value">100%</span>${iconBtn('zoom-in','+',t('zoomIn'))}${iconBtn('center','⌖',t('resetView'))}${iconBtn('fullscreen','⛶',t('fullscreen'))}</div><div id="call-banner" class="call-banner" role="status" aria-live="polite"></div><div id="pause-label" class="pause-label" hidden>${t('paused')}</div><div id="stage-hint" class="stage-hint"></div><aside id="detail-panel" class="detail-panel" hidden></aside></section></main>
 <footer class="build-dock"><button class="dock-heading" data-action="toggle-build"><span class="dock-icon">▦</span><div><b>${t('build')}</b><small>${copy('Choose a room','Raum auswählen')}</small></div></button><div class="room-palette" id="room-palette"></div><button class="inspect-button" data-action="inspect" title="${t('inspect')}">↖<span>${t('inspect')}</span></button></footer>
 <div id="modal-root"></div><div id="toast" class="toast" role="status" aria-live="polite"></div><input type="file" accept="application/json,.json" id="import-file" hidden>`;
 renderer=new Renderer($('#hospital-canvas'),{onBuild(type,rect){if(startScreen)return;if(result(game.addRoom(type,rect),t('built'))){buildType=null;renderer.buildType=null;if(autosaveEnabled)save(false);}},onSelect(type,id){if(startScreen)return;selected=type?{type,id}:null;if(type==='patient')game.readChart(id);renderer.selected=selected;panel=type==='staff'?'staff':type?'inspect':null;renderUI();}});renderer.lang=lang;
 $('#import-file').addEventListener('change',importSave);renderUI();}
let renderer;
function renderStart(){
 document.body.classList.add('tutorial-mode');
 patchHTML($('#vitals'),`<div class="vital balance"><span class="stat-icon">＄</span><div><small>${t('startCapital')}</small><b>${money(50000)}</b></div></div>`);
 patchHTML($('#sidebar'),`<div class="start-intro"><span class="eyebrow">${t('guideClass')}</span><h1>${t('emptyStartTitle')}</h1><p>${t('emptyStartText')}</p><div class="start-actions">${btn('new-game',t('startGuided')+' →','primary full','data-mode="tutorial" data-level="1"')}${savedGame?btn('resume-game',t('resumeClinic'),'secondary full'):''}${btn('episodes',t('otherModes'),'text-button full')}</div><ol class="start-steps">${[1,2,3].map(i=>`<li><b>${t('startStep'+i)}</b><span>${t('startStep'+i+'Text')}</span></li>`).join('')}</ol><p class="start-goal">${t('startGoal')}</p>${savedGame?`<div class="resume-card"><h2>${t('savedClinic')}</h2><p>${savedGame.rooms.length} ${t('rooms')} · ${money(savedGame.cash)}<br>${t('year')} ${savedGame.year} · ${t('month')} ${savedGame.month}</p>${btn('export',t('export'),'text-button full')}</div>`:savedSource?`<div class="resume-card"><p>${t('unreadableStartSave')}</p>${btn('export',t('export'),'secondary full')}</div>`:''}</div>`);
 $('#stage-status').textContent=t('planning');$('#stage-hint').textContent=t('startFloorHint');renderer.guideRect=null;
}
function renderUI(){
 document.body.classList.toggle('start-screen',startScreen);if(startScreen){renderStart();return;}
 $('#stage-status').textContent=t(game.admissionsOpen?'schedule':'planning');
 const focused=document.activeElement,focusAttrs=focused?.dataset?.action?Array.from(focused.attributes).filter(a=>a.name.startsWith('data-')).map(a=>`[${a.name}="${a.value}"]`).join(''):null;
 const active=game.patients.filter(p=>p.state!=='exit').length,guide=game.guide(),tutorial=game.mode==='tutorial';
 patchHTML($('#vitals'),`<div class="vital balance"><span class="stat-icon">＄</span><div><small>${t('cash')}</small><b class="${game.cash<0?'negative':''}">${money(game.cash)}</b></div></div><div class="vital"><span class="stat-icon star">${tutorial?'↗':'★'}</span><div><small>${t(tutorial?'annualProfit':'reputation')}</small><b>${tutorial?money(game.yearlyProfit()):Math.round(game.rep)}${tutorial?'':'<em>/100</em>'}</b></div></div><div class="vital"><span class="stat-icon heart">♡</span><div><small>${t('cured')}</small><b>${game.cured}<em>${game.mode==='campaign'?' / '+currentLevel().goal:''}</em></b></div></div>`);
 $('#episode-label').textContent=tutorial?t('tutorial'):game.mode==='sandbox'?t('sandbox'):`${t('level')} 0${game.level} · ${label(currentLevel().name)}`;
 patchHTML($('#time-controls'),`<span class="day-label"><span>◷</span> ${t('yearShort')}${game.year} · ${t('monthShort')}${String(game.month).padStart(2,'0')}</span>${btn('pause',paused?'▶':'Ⅱ',`time-button ${paused?'active':''}`,`title="${paused?t('play'):t('pause')}" aria-label="${paused?t('play'):t('pause')}"`)}${[1,2,3].map(n=>btn('speed',`${n}×`,`time-button ${speed===n?'active':''}`,`data-speed="${n}" aria-pressed="${speed===n}"`)).join('')}`);
 const annual=game.annualReport(),lastYear=game.financialYears.at(-1),objective=tutorial?Math.min(1,Math.max(0,annual.profit/ANNUAL_TARGET)):Math.min(1,game.cured/currentLevel().goal);
 patchHTML($('#sidebar'),`<div class="shift-heading"><span class="eyebrow">${tutorial?t('tutorial').toUpperCase():game.mode==='sandbox'?t('sandbox').toUpperCase():t('level').toUpperCase()+' 0'+game.level}</span><h1>${tutorial?t('tutorialName'):game.mode==='sandbox'?t('morning'):label(currentLevel().name)}</h1></div>
 ${guide?`<article class="guide-card"><div class="guide-kicker"><span>${t('guideClass')}</span><b>${guide.index+1} / ${GUIDE.length}</b></div><div class="guide-dots">${GUIDE.map((_,i)=>`<i class="${i<=guide.index?'done':''}"></i>`).join('')}</div><h2>${label(guide.title)}</h2><p>${label(guide.text)}</p>${guideButton(guide)}</article>`:''}
 <div class="objective-card"><div class="section-label">${t(tutorial?'annualGoal':'goal')} <span>⚑</span></div>${game.mode==='sandbox'?`<p>${t('free')}</p>`:`<div class="objective-row"><span>${t(tutorial?'profitAfterCosts':'cured')}</span><b>${tutorial?money(annual.profit):game.cured}</b></div><div class="progress-track"><i style="width:${objective*100}%"></i></div><div class="objective-row secondary"><span>${tutorial?t('annualTarget'):'★ '+t('reputation')}</span><b>${tutorial?'':Math.round(game.rep)+' / '+currentLevel().rep}</b></div>`}${tutorial?`<div class="year-track"><span>${t('year')} ${game.year}</span><b>${game.month}/12</b></div><div class="thin-progress"><i style="width:${(game.calendar%YEAR_SECONDS)/YEAR_SECONDS*100}%"></i></div>${lastYear?`<p class="last-year">${t('closedYear')} ${lastYear.year}: <b>${money(lastYear.profit)}</b></p>`:''}`:''}</div>
 <div class="flow-card"><div class="section-label">${t('patientFlow')}</div><div class="flow-total"><b>${active}</b><span>${t('patients').toLowerCase()}</span></div><div class="flow-steps">${[['reception','▤'],['diagnosis','✚'],['treatment','♡']].map(([stage,icon])=>`<div><span>${icon}</span><b>${game.patients.filter(p=>p.stage===stage).length}</b><small>${t(stage==='reception'?'registration':stage)}</small></div>`).join('')}</div><div class="waiting-summary"><span>▥ ${t('seatsOccupied')}</span><b>${game.seatStats().reserved} / ${game.seatStats().capacity}</b><small>${game.seatStats().standing} ${t('standingQueue')}</small></div><div class="health-line"><span>✧ ${t('cleanliness')}</span><b>${Math.round(game.cleanliness)}%</b></div><div class="thin-progress"><i style="width:${game.cleanliness}%"></i></div></div>
 ${game.mode==='campaign'?`<div class="story-objectives"><span class="section-label">${t('storyBriefing')}</span><p>${label(currentLevel().desc)}</p>${currentLevel().specialty?`<div class="finance-row"><span>${label(ROOMS[currentLevel().specialty].name)}</span><b>${game.curedByRoom[currentLevel().specialty]||0}/${currentLevel().specialtyGoal}</b></div><div class="finance-row"><span>${label(PROJECTS.find(p=>p.id===currentLevel().project).name)}</span><b>${game.completed.includes(currentLevel().project)?'✓':'○'}</b></div>`:''}</div>`:''}<div class="radio"><div class="section-label">${t('alerts')}</div><p>${game.logs[0]?formatLog(game.logs[0]):t('noAlerts')}</p></div>`);
 patchHTML($('#room-palette'),Object.entries(ROOMS).map(([type,r])=>`<button class="room-card ${buildType===type?'selected':''}" data-action="build" data-type="${type}" ${game.available(type)?'':'disabled'} aria-pressed="${buildType===type}"><span class="room-symbol" style="--room-color:${r.color}">${r.icon}</span><span class="room-card-text"><b>${label(r.name)}</b><small>${game.available(type)?money(r.cost):'⌑ '+t('level')+' '+(type==='therapy'?2:3)}</small></span></button>`).join(''));
 $('#clinic-open').hidden=game.admissionsOpen;
 document.body.classList.toggle('tutorial-mode',tutorial);document.body.classList.toggle('build-open',buildOpen||!!buildType);$('#room-palette').hidden=!(buildOpen||buildType);
 $('#voice-control').textContent=voice.ready&&voice.enabled?copy('🔊 Announcements on','🔊 Durchsagen an'):copy('🔈 Enable announcements','🔈 Durchsagen einschalten');
 const latest=game.calls.at(-1);patchHTML($('#call-banner'),latest?`<span>📣</span><div><small>${copy('Latest call','Letzter Aufruf')}</small><b>${escape(callText(latest))}</b></div>`:'');$('#call-banner').hidden=!latest;

 patchHTML($('#stage-hint'),buildType?`<span class="build-mode-dot"></span><b>${label(ROOMS[buildType].name)}</b><span>${t('buildHint')}</span>${btn('inspect','×','','aria-label="'+t('cancel')+'"')}`:`<span>↖</span> ${t(game.admissionsOpen?'selectHint':'planningHint')}`);
 $('#stage-hint').classList.toggle('building',!!buildType);$('#pause-label').hidden=!paused;$('#zoom-value').textContent=Math.round(renderer.zoom*100)+'%';
 renderer.guideRect=guide?.rect?{...guide.rect,type:guide.room}:null;
 document.querySelectorAll('[data-action="panel"]').forEach(b=>{b.classList.toggle('active',b.dataset.panel===panel);b.classList.remove('guide-highlight');});
 renderPanel();if(focusAttrs&&!document.contains(focused))document.querySelector(focusAttrs)?.focus({preventScroll:true});
}
function guideButton(guide){
 if(guide.room)return btn('guide-place',`${t('placeGuide')} · ${money(ROOMS[guide.room].cost)}`,'primary full')+btn('guide-build',t('selectRoom'),'text-button full');
 if(guide.cast)return btn('guide-hire',t('compareApplicants')+' →','primary full');
 if(guide.upgrade){const r=game.rooms.find(r=>r.type===guide.upgrade);return btn('guide-upgrade',`${t('upgradeGuide')} · ${money(Math.round(ROOMS[r.type].cost*.65*r.level))}`,'primary full');}
 if(guide.id==='open')return btn('open-clinic',t('openClinic')+' →','primary full');
 if(guide.id==='chart')return btn('patient-chart',t('viewChart')+' →','primary full',`data-id="${game.records[0]?.id}"`);
 if(guide.id==='profit')return btn('panel',t('viewAccounts'),'secondary full','data-panel="finances"');
 return `<div class="guide-watching">◷ ${guide.id==='cures'?`${game.cured} / 3 ${t('cured')}`:t('firstArrival')}</div>`;
}

function formatLog(l){let extra=l.extra;if(ROOMS[extra])extra=label(ROOMS[extra].name);if(PROJECTS.some(p=>p.id===extra))extra=label(PROJECTS.find(p=>p.id===extra).name);if(l.code==='paid')extra=money(Number(extra));return `${escape(t(l.code))}${extra?' · '+escape(extra):''}`;}
function panelHeader(title,kicker){return `<div class="panel-header"><div><small>${kicker}</small><h2>${title}</h2></div>${iconBtn('close-panel','×',t('close'))}</div>`;}
function renderPanel(){const el=$('#detail-panel'),scrollTop=el.querySelector('.panel-scroll')?.scrollTop||0;el.hidden=!panel;let html='';if(!panel)return;
 if(panel==='queue'){html=queuePanel();}
 else if(panel==='patients'){html=patientDirectory();}
 else if(panel==='staff'){html=panelHeader(t('team'),`${game.staff.length} ${t('hired')}`)+`<div class="panel-scroll"><h3 class="recruit-label">${t('compareApplicants')}</h3><p class="panel-intro">${t('recruitIntro')}</p><div class="recruit-tabs">${ROLES.map(role=>btn('recruit-role',t(role),recruitRole===role?'active':'',`data-role="${role}"`)).join('')}</div><div class="applicant-list">${game.applicants(recruitRole).map(s=>`<article class="recruit-card applicant-card">${avatar(s)}<div><span class="applicant-tier">${t(s.personality)}</span><b>${escape(s.name)}</b><p>${label(PERSONALITIES[s.personality])}</p><div class="applicant-stats"><span>${t('skill')} <b>${Math.round(s.skill*100)}%</b></span><span>${t('monthlySalary')} <b>${money(s.wage)}</b></span></div>${btn('hire-applicant',`${t('hire')} · ${money(s.hire)}`,'small-button',`data-applicant="${s.id}" ${game.cash<s.hire?'disabled':''}`)}</div></article>`).join('')||`<p class="panel-intro">${t('noApplicants')}</p>`}</div>${btn('refresh-applicants',`${t('refreshApplicants')} · ${money(RECRUITMENT_FEE)}`,'secondary full',game.cash<RECRUITMENT_FEE?'disabled':'')}<p class="recruit-note">${t('recruitFeeHint')}</p><h3 class="recruit-label">${t('hired')}</h3>${game.staff.map(s=>{const r=game.room(s.roomId);return `<article class="employee-card">${avatar(s)}<div class="employee-info"><b>${escape(s.name)}</b><span>${t(s.role)} · ${staffStatus(s)}${r?' · '+label(ROOMS[r.type].name):''}</span><div class="fatigue-line"><i style="width:${s.fatigue}%;background:${s.fatigue>70?'#c28455':'#b9cb9c'}"></i></div><small>${t('fatigue')} ${Math.round(s.fatigue)}% · ${money(s.wage)} / ${t('month')}</small><small>${t('skill')} ${Math.round(s.skill*100)}% · ${escape(s.personality?t(s.personality):t('steady'))}</small></div>${btn('staff-break',s.breakPending?copy('Break requested','Pause vorgemerkt'):copy('Take a break','Pause machen'),'staff-break',`data-id="${s.id}" ${s.resting||s.breakPending?'disabled':''}`)}${btn('dismiss-staff','×','dismiss-button',`data-id="${s.id}" title="${t('dismiss')}"`)}</article>`;}).join('')}</div>`;
 }else if(panel==='research'){html=panelHeader(t('research'),'R&D')+`<div class="panel-scroll"><p class="panel-intro">${t('noResearch')}</p>${PROJECTS.map(p=>{const done=game.completed.includes(p.id),active=game.project?.id===p.id;return `<article class="project-card"><span class="project-icon">${done?'✓':'⚗'}</span><h3>${label(p.name)}</h3><p>${label(p.desc)}</p>${active?`<div class="progress-track"><i style="width:${game.project.progress/p.time*100}%"></i></div><small>${t('researching')} · ${Math.round(game.project.progress/p.time*100)}%</small>`:btn('research',done?'✓ '+t('researched'):`${t('startResearch')} · ${money(p.cost)}`,'small-button',`data-project="${p.id}" ${done||game.project?'disabled':''}`)}</article>`;}).join('')}</div>`;
 }else if(panel==='finances'){const report=game.annualReport();html=panelHeader(t('finances'),`${t('year')} ${game.year}`)+`<div class="panel-scroll"><div class="finance-balance"><small>${t('annualProfit')}</small><b class="${report.profit<0?'negative':''}">${money(report.profit)}</b></div><p class="panel-intro">${t('profitRule')}</p>${[[t('income'),report.income],[t('expenses'),-report.expenses],[t('construction'),-report.construction],[t('profitAfterCosts'),report.profit]].map(([k,v])=>`<div class="finance-row"><span>${k}</span><b class="${v<0?'negative':'positive'}">${money(v)}</b></div>`).join('')}<div class="daily-cost"><span>${t('monthlyCost')}</span><b>${money(game.dailyCost())}</b></div><p class="panel-intro">${t('calendarRule')}</p>${game.contracts.length?`<div class="loan-card"><span>♠ ${t('loanRepayments')}</span><b>${money(game.debtRemaining())}</b><p>${t('loanRule')}</p></div>`:''}${game.modifiers.length?`<div class="loan-card"><span>${t('activeChallenges')}</span>${game.modifiers.map(m=>`<p>${t(m.kind)} · ${Math.ceil(m.endsAt-game.clock)}s</p>`).join('')}</div>`:''}<h3>${t('closedYear')}</h3>${game.financialYears.length?game.financialYears.slice().reverse().map(y=>`<div class="finance-row"><span>${t('year')} ${y.year}</span><b class="${y.profit>=ANNUAL_TARGET?'positive':''}">${money(y.profit)}</b></div>`).join(''):`<p class="panel-intro">${t('noClosedYear')}</p>`}<h3>${t('costs')}</h3>${game.ledger.map(l=>`<div class="finance-row"><span>${t('yearShort')}${l.year||1} · ${t('monthShort')}${l.day}</span><b>−${money(l.cost)}</b></div>`).join('')}</div>`;
 }else if(panel==='inspect'){if(selected?.type==='room'){const r=game.room(selected.id);if(!r){panel=null;el.hidden=true;return;}const type=ROOMS[r.type],s=game.staff.find(s=>s.id===r.staffId);html=panelHeader(label(type.name),t('roomDetails'))+`<div class="panel-scroll"><div class="room-detail-symbol" style="background:${type.color}">${type.icon}</div><p class="panel-intro">${label(type.desc)}</p>${r.type==='waiting'?`<div class="waiting-detail"><b>${game.patients.filter(p=>p.seatRoom===r.id).length} / ${game.seats(r).length} ${t('seatsOccupied')}</b><p>${t('seatComfort')} ${Math.round((.65+(r.level-1)*.05)*100)}%</p></div>`:''}<div class="room-status" ${!type.role?'hidden':''}>${s?avatar(s):'<span>♟</span>'}<div><b>${s?escape(s.name):t('uncovered')}</b><small>${s?staffStatus(s):t('noStaff')}</small></div></div><div class="detail-grid">${[[t('levelWord'),r.level+'/3'],[t('queue'),game.queue(r)],[t('condition'),Math.round(r.condition)+'%'],[t('success'),type.time?Math.round(game.success(r)*100)+'%':'—']].map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('')}</div>${r.level<3?btn('upgrade',`${t('upgrade')} · ${money(Math.round(type.cost*.65*r.level))}`,'primary full',`data-id="${r.id}"`):`<p>${t('maxLevel')}</p>`}<h3 class="chart-section">${copy('In this room','In diesem Raum')}</h3>${roomObjects(r).map(o=>btn('object',labelObject(o,0),'object-link',`data-object="${o.id}"`)).join('')}${btn('sell',`${t('sell')} · +${money(Math.round(type.cost*.5))}`,'text-button full',`data-id="${r.id}"`)}</div>`;
 }else if(selected?.type==='object'){html=objectPanel(selected.id);}else if(selected?.type==='patient'){const record=game.record(selected.id);if(!record){panel=null;el.hidden=true;selected=null;return;}html=patientChart(record);}else{panel=null;el.hidden=true;}}
 patchHTML(el,html);el.classList.toggle('chart-panel',panel==='patients'||selected?.type==='patient');const scroller=el.querySelector('.panel-scroll');if(scroller)scroller.scrollTop=scrollTop;
}
function patientDirectory(){const records=game.records.filter(r=>patientFilter==='all'||(patientFilter==='active'?r.dischargedAt===null:r.dischargedAt!==null)).slice().reverse();return panelHeader(t('casebook'),`${game.records.length} ${t('patientCount')}`)+`<div class="patient-filters">${[['active','activePatients'],['discharged','dischargedPatients'],['all','all']].map(([value,key])=>btn('patient-filter',t(key),patientFilter===value?'active':'',`data-filter="${value}"`)).join('')}</div><div class="panel-scroll">${records.length?records.map(r=>{const live=game.patients.find(p=>p.id===r.id);return `<button class="patient-row" data-action="patient-chart" data-id="${r.id}"><span class="patient-mini"><img src="${patientPortrait(r)}" alt=""/></span><span class="patient-row-main"><small>${r.number}</small><b>${escape(r.name)}</b><span>${live?t(live.stage==='exit'?'departing':live.stage==='reception'?'checkInFirst':live.stage):t(r.outcome==='cured'?'chartCured':r.outcome==='left'?'chartLeft':'chartFailed')}</span></span><span class="patient-arrow">↗</span></button>`;}).join(''):`<p class="panel-intro">${t(game.records.length?'noMatchingPatients':'noPatients')}</p>`}</div>`;}
function patientChart(record){
 const live=game.patients.find(p=>p.id===record.id),illness=ILLNESSES.find(i=>i.id===record.illness),date=record.birthDate.split('-').reverse().join('.'),status=record.dischargedAt===null?t('chartActive'):t(record.outcome==='cured'?'chartCured':record.outcome==='left'?'chartLeft':'chartFailed');
 return panelHeader(escape(record.name),`${t('patientFile')} · ${record.number}`)+`<div class="panel-scroll"><button class="back-patients" data-action="panel" data-panel="patients">← ${t('backToPatients')}</button><div class="chart-hero"><img src="${patientPortrait(record)}" alt="${escape(record.name)}"/><div><span class="chart-number">${record.number}</span><h3>${escape(record.name)}</h3><span class="chart-status ${record.outcome||''}">${status}</span><p>${escape(t(record.priority))} · ${record.age} ${t('yearsOld')}</p></div></div><h3 class="chart-section">${t('personalDetails')}</h3><dl class="personal-grid">${[[t('dateOfBirth'),date],[t('occupation'),label(PATIENT_FACTS.occupation[record.occupation])],[t('insurance'),label(PATIENT_FACTS.insurance[record.insurance])],[t('allergies'),label(PATIENT_FACTS.allergy[record.allergy])],[t('admission'),`${t('yearShort')}${record.admittedYear} · ${t('monthShort')}${record.admittedMonth}`],[t('discharge'),record.dischargedAt===null?t('stillHere'):`${t('yearShort')}${record.timeline.at(-1)?.year} · ${t('monthShort')}${record.timeline.at(-1)?.month}`]].map(([k,v])=>`<div><dt>${k}</dt><dd>${escape(v)}</dd></div>`).join('')}</dl><h3 class="chart-section">${t('complaint')}</h3><blockquote class="patient-quote">${record.age<16?copy('“My teddy says it is probably homework fever.”','„Mein Teddy sagt, es ist bestimmt Hausaufgabenfieber.“'):label(COMPLAINTS[record.illness])}</blockquote><div class="chart-diagnosis"><span>✚</span><div><small>${t('diagnosis')}</small><b>${record.diagnosed?label(illness.name):t('diagnosisPending')}</b></div></div>${live?`<p class="patient-location">${t(live.state==='seated'?'patientSeated':live.state==='seatTravel'?'goingToSeat':live.state==='roomExit'?'leavingRoom':live.state==='queue'?'standingQueue':['called','inside'].includes(live.state)?'calledIn':live.state==='service'?'working':'waiting')} ${live.seatRoom?`· ${t('seatNumber')} ${live.seatIndex+1}`:''}</p><div class="objective-row"><span>${t('health')}</span><b>${Math.round(live.patience)}%</b></div><div class="progress-track"><i style="width:${live.patience}%"></i></div>`:''}<h3 class="chart-section">${t('invoice')}</h3>${[[t('registrationFee'),0],[t('diagnosisCharge'),record.diagnosisCharge],[t('treatmentCharge'),record.treatmentCharge],[t('totalBilled'),record.bill]].map(([k,v])=>`<div class="finance-row"><span>${k}</span><b>${money(v)}</b></div>`).join('')}<h3 class="chart-section">${t('careTimeline')}</h3><ol class="care-timeline">${record.timeline.map(e=>`<li><small>${t('yearShort')}${e.year} · ${t('monthShort')}${e.month} · ${Math.floor(e.time%30)}s</small><b>${escape(e.code==='called'?copy('Called by the clinician','Vom Behandler aufgerufen'):t(e.code))}</b>${e.roomType?`<span>${escape(label(ROOMS[e.roomType]?.name||e.roomType))}${e.staffName?' · '+escape(e.staffName):''}</span>`:''}${e.amount?`<span>${money(e.amount)}</span>`:''}</li>`).join('')}</ol></div>`;
}

function labelObject(o,index){return OBJECT_INFO[o.kind][index][lang==='de'?1:0];}
function objectPanel(id){const o=findObject(game,id);if(!o)return panelHeader(copy('Object removed','Gegenstand entfernt'),'');const r=game.room(o.roomId);return panelHeader(labelObject(o,0),label(ROOMS[r.type].name))+`<div class="panel-scroll"><div class="object-illustration">${({sofa:'🛋',chair:'🪑',toys:'🧸',door:'🚪',plant:'🪴',books:'📚',bell:'🛎',monitor:'🖥',gp:'🦆',pharmacy:'☕',sink:'🫧',toilet:'🚽'})[o.kind]||'✨'}</div><p class="object-description">${labelObject(o,1)}</p>${o.kind==='door'?btn('door',r.doorHeld?copy('Return to automatic','Wieder automatisch schließen'):copy('Hold door open','Tür offen halten'),'primary full',`data-id="${r.id}"`):''}<div class="object-facts"><span>${copy('Included in the room','Im Raum enthalten')}</span><b>${copy('Room level','Raumstufe')} ${r.level}/3</b></div>${btn('room',copy('Inspect this room','Raum ansehen'),'secondary full',`data-id="${r.id}"`)}</div>`;}
function queuePanel(){const list=game.waitingList(),called=game.patients.filter(p=>['called','inside','service'].includes(p.state)&&p.registered);return panelHeader(copy('Waiting list','Warteliste'),copy('Reception → waiting → call → care','Anmeldung → Warten → Aufruf → Behandlung'))+`<div class="panel-scroll"><p class="panel-intro">${copy('Reception creates each appointment. The next available clinician calls patients in registration order for their department.','Die Rezeption legt jeden Termin an. Der nächste freie Behandler ruft die Patienten in der Anmeldereihenfolge seiner Abteilung auf.')}</p>${called.map(p=>`<div class="queue-current">${p.state==='service'?'🩺':'📣'} <b>${escape(p.name)}</b><small>${label(ROOMS[game.room(p.targetRoom).type].name)} · ${copy(p.state==='service'?'In consultation':'Called',p.state==='service'?'In Behandlung':'Aufgerufen')}</small></div>`).join('')}${game.rooms.filter(r=>ROOMS[r.type].role&&!game.staffReady(game.staff.find(s=>s.id===r.staffId))).map(r=>{const s=game.staff.find(s=>s.id===r.staffId);return `<p class="queue-current"><b>${label(ROOMS[r.type].name)} · ${r.id}</b><small>${s?staffStatus(s):copy('No staff assigned','Kein Personal zugeteilt')}</small></p>`;}).join('')}<h3 class="chart-section">${list.length} ${copy('waiting appointments','wartende Termine')}</h3>${list.map((p,i)=>`<button class="queue-row" data-action="patient-chart" data-id="${p.id}"><span>${i+1}</span><div><b>${p.child?'🧸 ':''}${escape(p.name)}</b><small>${label(ROOMS[game.need(p)].name)} · ${copy(p.state==='seated'?'Seated':'Waiting',p.state==='seated'?'Sitzt':'Wartet')}</small></div><span>↗</span></button>`).join('')||`<p class="panel-intro">${copy('No registered appointments waiting.','Keine angemeldeten Termine warten.')}</p>`}${btn('panel',copy('All patient records','Alle Patientenakten'),'secondary full','data-panel="patients"')}</div>`;}

let previousFocus=null;
function openModal(type,extra){voice.suspend(true);previousFocus=document.activeElement;modal={type,extra};renderModal();}
function closeModal(){modal=null;$('#modal-root').innerHTML='';document.querySelector('.topbar').inert=false;document.querySelector('.workbar').inert=false;document.querySelector('.game-shell').inert=false;document.querySelector('.build-dock').inert=false;previousFocus?.focus();}
function renderModal(){if(!modal)return;let html='',wide=false;const type=modal.type;
 if(type==='welcome'){html=`<div class="modal-body"><span class="eyebrow">${game.mode==='campaign'?t('campaign'):t('sandbox')}</span><h2>${game.mode==='campaign'?label(currentLevel().name):t('emptyStartTitle')}</h2><p class="modal-subtitle">${game.mode==='campaign'?label(currentLevel().desc):t('sandboxDesc')}</p><ol class="start-steps">${[1,2,3].map(i=>`<li><b>${t('startStep'+i)}</b><span>${t('startStep'+i+'Text')}</span></li>`).join('')}</ol><p class="start-goal">${t('startFloorHint')}</p>${btn('close-modal',t('startBuilding')+' →','primary full')}</div>`;
 }else if(type==='help'){wide=true;html=`<div class="modal-body"><span class="eyebrow">${lang==='de'?'DIE EINWEISUNG, DIE EINE E-MAIL HÄTTE SEIN KÖNNEN':'THE ORIENTATION THAT COULD HAVE BEEN AN EMAIL'}</span><h2>${t('help')}</h2><p class="modal-subtitle">${t('guideSubtitle')}</p><div class="guide-grid">${[1,2,3,4,5].map(i=>`<div><span class="guide-number">0${i}</span><h3>${t('guide'+i)}</h3><p>${t('guide'+i+'Text')}</p></div>`).join('')}</div><p class="keyboard-guide">${t('controls')}</p>${btn('close-modal',t('gotIt')+' →','primary')}</div>`;
 }else if(type==='episodes'){wide=true;html=`<div class="modal-body"><span class="eyebrow">SCRUBSSITEL</span><h2>${t('selectEpisode')}</h2><div class="tutorial-episode-card"><div><span class="eyebrow">${t('orientation')}</span><h3>${t('tutorial')}</h3><p>${t('tutorialIntro')}</p></div>${btn('new-game',t('startTutorial')+' →','primary','data-mode="tutorial" data-level="1"')}</div><div class="episode-grid">${LEVELS.map(l=>{const locked=l.id>1&&!progress.includes(l.id-1);return `<article class="episode-card ${locked?'locked':''}"><span class="episode-number">0${l.id}</span><span class="eyebrow">${t('level')} ${l.id} ${progress.includes(l.id)?'★':''}</span><h3>${label(l.name)}</h3><p>${label(l.desc)}</p>${btn('new-game',locked?'⌑ '+t('locked'):t('start')+' →','small-button',`data-level="${l.id}" data-mode="campaign" ${locked?'disabled':''}`)}</article>`;}).join('')}</div><div class="sandbox-card"><div><h3>∞ ${t('sandbox')}</h3><p>${t('sandboxDesc')}</p></div>${btn('new-game',t('start')+' →','primary','data-mode="sandbox" data-level="1"')}</div></div>`;
 }else if(type==='settings'){html=`<div class="modal-body"><span class="eyebrow">SCRUBSSITEL</span><h2>${t('settings')}</h2><label class="settings-row">${t('language')}<select id="language-select"><option value="auto" ${!prefs.lang||prefs.lang==='auto'?'selected':''}>${t('auto')}</option><option value="en" ${prefs.lang==='en'?'selected':''}>English</option><option value="de" ${prefs.lang==='de'?'selected':''}>Deutsch</option></select></label><div class="settings-row"><span>${t('sound')}</span>${btn('sound',prefs.sound?t('on'):t('off'),'toggle '+(prefs.sound?'enabled':''),'aria-pressed="'+!!prefs.sound+'"')}</div><p class="panel-intro">${t('autoSave')}</p><div class="save-buttons">${btn('export','↓ '+t('export'),'secondary')}${btn('import','↑ '+t('import'),'secondary')}</div>${btn('episodes',t('newGame'),'text-button full')}${btn('delete-save',t('deleteSave'),'text-button full danger')}<p class="credits">${t('credits')}</p><a class="source-link" href="https://github.com/MarcelWeissgerberIT/scrubssitel" target="_blank" rel="noopener">GitHub ↗</a></div>`;
 }else if(type==='event'){const ev=EVENTS.find(e=>e.id===game.event);if(!ev){closeModal();return;}html=`<div class="modal-body event-body"><span class="eyebrow">${t('event')}</span><div class="event-emoji">${{coffee:'☕',review:'★',grant:'✉',rush:'⚡',mafia:'♠',printer:'▤',inspection:'♧',influencer:'✦'}[ev.id]}</div><h2>${label(ev.name)}</h2><p>${label(ev.text)}</p><div class="event-choices">${ev.choices.map((c,i)=>btn('event-choice',label(c.label),'secondary',`data-choice="${i}" ${c.cost>0&&game.cash<c.cost?'disabled':''}`)).join('')}</div></div>`;
 }else if(type==='tutorial-win'){html=`<div class="modal-body win-body"><span class="win-icon">★</span><h2>${t('guideFinished')}</h2><p>${t('tutorialWin')}</p><div class="finance-balance"><small>${t('bestYear')}</small><b>${money(Math.max(...game.financialYears.map(y=>y.profit)))}</b></div>${btn('close-modal',t('keepPlaying'),'primary full')}${btn('episodes',t('selectEpisode'),'text-button full')}</div>`;
 }else if(type==='win'||type==='over'){html=`<div class="modal-body win-body"><span class="win-icon">${type==='win'?'★':'☂'}</span><span class="eyebrow">${t('level')} 0${game.level}</span><h2>${t(type==='win'?'win':'gameOver')}</h2><p>${t(type==='win'?'winText':'gameOverText')}</p><div class="win-stats"><span><b>${game.cured}</b>${t('cured')}</span><span><b>${Math.round(game.rep)}</b>${t('reputation')}</span><span><b>${money(game.cash)}</b>${t('cash')}</span></div>${type==='win'?(game.level<3?btn('next',t('nextEpisode')+' →','primary full'):`<p>${t('completedCampaign')}</p>`)+btn('close-modal',t('keepPlaying'),'text-button full'):btn('retry',t('retry'),'primary full')}</div>`;
 }else if(type==='confirm'){html=`<div class="modal-body"><h2>${t(modal.extra.title)}</h2><p>${t(modal.extra.text)}</p><div class="modal-actions">${btn('confirm',t('yes'),'primary')}${btn('close-modal',t('cancel'),'secondary')}</div></div>`;}
 $('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${wide?'wide':''} ${type==='welcome'?'setup-modal':''}" role="dialog" aria-modal="true" aria-label="${escape(type==='welcome'?t('guideTitle'):type==='event'?t('event'):t(type==='episodes'?'selectEpisode':type==='over'?'gameOver':type))}">${!['welcome','event','over','win','confirm'].includes(type)?iconBtn('close-modal','×',t('close')):''}${html}</section></div>`;
 for(const selector of ['.topbar','.workbar','.game-shell','.build-dock'])$(selector).inert=true;
 requestAnimationFrame(()=>$('#modal-root button:not(:disabled)')?.focus());
 $('#language-select')?.addEventListener('change',e=>{prefs.lang=e.target.value;persistPrefs();changeLanguage(prefs.lang==='auto'?detectLanguage():prefs.lang);});
}
function confirm(title,text,action){confirmAction=action;openModal('confirm',{title,text});}
function resumeGame(){readStoredClinic();if(!savedGame){renderUI();notify(t(savedSource?'badSave':'noSave'),true);return;}game=savedGame;startScreen=false;savedGame=null;savedSource=null;voice.reset(game.callSerial);lastCured=game.cured;winShown=game.won;overShown=false;paused=false;speed=1;panel=null;selected=null;buildType=null;buildOpen=false;renderer.selected=null;renderer.buildType=null;accumulator=0;autosaveEnabled=true;closeModal();renderUI();renderer.reset();renderer.resize();}
function newGame(mode,level){accumulator=0;startScreen=false;savedGame=null;savedSource=null;game=new Game({mode,level});voice.reset(0);buildOpen=false;lastCured=game.cured;paused=false;speed=1;selected=null;panel=null;buildType=null;winShown=false;overShown=false;renderer.selected=null;renderer.buildType=null;renderer.reset();autosaveEnabled=true;closeModal();save(false);renderUI();renderer.resize();if(mode!=='tutorial')openModal('welcome');}
function changeLanguage(next){voice.setLanguage(next);lang=next;t=translator(lang);const oldZoom=renderer.zoom,oldPan=renderer.pan;const oldModal=modal;shell();renderer.zoom=oldZoom;renderer.pan=oldPan;renderer.selected=selected;renderer.buildType=buildType;modal=oldModal;if(modal)renderModal();}
async function importSave(e){const input=e.target;try{const file=input.files[0];if(!file)return;if(file.size>25000000)throw Error('Too large');const data=JSON.parse(await file.text());const restored=Game.restore(data.game||data);startScreen=false;savedGame=null;savedSource=null;game=restored;voice.reset(game.callSerial);lastCured=game.cured;if(data.progress&&Array.isArray(data.progress))progress=data.progress.filter(x=>[1,2,3,'tutorial'].includes(x));selected=null;panel=null;renderer.selected=null;buildType=null;renderer.buildType=null;paused=true;winShown=game.won;overShown=false;autosaveEnabled=true;closeModal();save(false);renderUI();renderer.resize();notify(t('imported'));}catch{notify(t('badSave'),true);}input.value='';}
function exportSave(){if(startScreen){readStoredClinic();if(!savedSource){renderUI();notify(t('noSave'));return;}}const source=startScreen?savedGame:game;const blob=new Blob([source?JSON.stringify({game:source.snapshot(),progress},null,2):savedSource||'{}'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`scrubssitel-day-${source?.day||1}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('#app').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 switch(a){case 'voice':if(voice.enabled&&voice.ready)voice.mute();else voice.activate(lang);renderUI();break;case 'toggle-build':buildOpen=!buildOpen;buildType=null;renderer.buildType=null;renderUI();renderer.resize();break;case 'object':selected={type:'object',id:b.dataset.object};renderer.selected=selected;panel='inspect';renderUI();break;case 'door':game.toggleDoor(+b.dataset.id);renderUI();break;case 'room':selected={type:'room',id:+b.dataset.id};renderer.selected=selected;panel='inspect';renderUI();break;case 'pause':paused=!paused;renderUI();break;case 'speed':speed=+b.dataset.speed;paused=false;renderUI();break;case 'save':autosaveEnabled=true;save();break;case 'help':openModal('help');break;case 'settings':openModal('settings');break;case 'episodes':openModal('episodes');break;case 'close-modal':if(!game.event&&!game.over)closeModal();break;case 'switch-language':prefs.lang=lang==='en'?'de':'en';persistPrefs();changeLanguage(prefs.lang);break;case 'patient-filter':patientFilter=b.dataset.filter;renderUI();break;case 'patient-chart':selected={type:'patient',id:+b.dataset.id};game.readChart(selected.id);renderer.selected=selected;panel='inspect';renderUI();break;case 'guide-place':{const g=game.guide();if(g?.room&&result(game.addRoom(g.room,g.rect),t('built'))){renderer.buildType=null;buildType=null;renderUI();}break;}case 'guide-build':{const g=game.guide();if(g?.room){buildType=g.room;renderer.buildType=g.room;renderer.reset();renderer.canvas.focus();renderUI();}break;}case 'guide-hire':{const g=game.guide();if(g?.cast){recruitRole=CAST.find(c=>c.id===g.cast).role;panel='staff';renderUI();}break;}case 'guide-upgrade':{const g=game.guide(),r=game.rooms.find(r=>r.type===g?.upgrade);if(r)result(game.upgrade(r.id),t('upgraded'));break;}case 'open-clinic':if(result(game.openClinic(),t('clinicOpened')))voice.activate(lang);break;case 'panel':selected=null;renderer.selected=null;panel=panel===b.dataset.panel?null:b.dataset.panel;renderUI();break;case 'close-panel':panel=null;selected=null;renderer.selected=null;renderUI();break;
 case 'build':buildType=buildType===b.dataset.type?null:b.dataset.type;renderer.buildType=buildType;panel=null;selected=null;renderer.selected=null;renderUI();break;case 'inspect':buildOpen=false;buildType=null;renderer.buildType=null;renderer.drag=null;renderUI();break;case 'recruit-role':recruitRole=b.dataset.role;renderUI();break;case 'hire-applicant':result(game.hireApplicant(b.dataset.applicant),t('hireDone'));break;case 'refresh-applicants':result(game.refreshApplicants(),t('newApplicants'));break;case 'staff-break':game.requestBreak(+b.dataset.id);renderUI();break;case 'dismiss-staff':confirm('dismiss','dismissText',()=>result(game.dismiss(+b.dataset.id)));break;case 'upgrade':result(game.upgrade(+b.dataset.id),t('upgraded'));break;case 'sell':confirm('confirmSell','confirmSellText',()=>{if(result(game.sell(+b.dataset.id))){selected=null;panel=null;renderer.selected=null;}});break;case 'research':result(game.startResearch(b.dataset.project));break;
 case 'zoom-in':renderer.setZoom(renderer.zoom+.15);renderUI();break;case 'zoom-out':renderer.setZoom(renderer.zoom-.15);renderUI();break;case 'center':renderer.reset();renderUI();break;case 'fullscreen':if(!document.fullscreenElement){document.documentElement.requestFullscreen?.().catch(()=>{});}else document.exitFullscreen?.();break;
 case 'new-game':{const mode=b.dataset.mode,level=+b.dataset.level;if(startScreen)readStoredClinic();if(startScreen&&!savedSource)newGame(mode,level);else confirm('confirmNew','confirmNewText',()=>newGame(mode,level));break;}case 'resume-game':resumeGame();break;case 'confirm':{const action=confirmAction;closeModal();action?.();renderUI();break;}case 'next':newGame('campaign',Math.min(3,game.level+1));break;case 'retry':newGame(game.mode,game.level);break;
 case 'sound':prefs.sound=!prefs.sound;persistPrefs();chime();renderModal();break;case 'export':exportSave();break;case 'import':$('#import-file').click();break;case 'delete-save':confirm('deleteSave','deleteSaveText',()=>{try{localStorage.removeItem('scrubssitel-save');localStorage.removeItem('scrubssitel-progress');progress=[];autosaveEnabled=false;notify(t('deleted'));}catch{notify(t('saveFailed'),true);}});break;
 case 'event-choice':if(result(game.resolveEvent(+b.dataset.choice))){closeModal();if(autosaveEnabled)save(false);}break;
 }});
document.addEventListener('keydown',e=>{if(modal){if(e.key==='Tab'){const items=[...document.querySelectorAll('#modal-root button:not(:disabled), #modal-root select, #modal-root a')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}if(e.key==='Escape'&&!['event','over','win','welcome'].includes(modal.type))closeModal();return;}if(startScreen)return;if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement?.tagName)&&e.key!=='Escape')return;if(e.code==='Space'){e.preventDefault();paused=!paused;renderUI();}if(['1','2','3'].includes(e.key)){speed=+e.key;paused=false;renderUI();}if(e.key.toLowerCase()==='b'){buildType=buildType?null:'gp';renderer.buildType=buildType;renderer.canvas.focus();renderUI();}if(e.key==='Escape'){buildType=null;renderer.buildType=null;renderer.drag=null;panel=null;renderUI();}});
window.addEventListener('beforeunload',()=>{if(autosaveEnabled)save(false);});
document.addEventListener('visibilitychange',()=>{voice.suspend(document.hidden||paused||!!modal);if(document.hidden&&autosaveEnabled)save(false);});
shell();renderer.resize();
let last=performance.now(),accumulator=0,lastUI=0,lastCured=game.cured,animationTime=0;
function frame(now){voice.suspend(paused||!!modal||document.hidden||game.over);const elapsed=Math.min((now-last)/1000,.25);last=now;
 if(!startScreen&&!paused&&!modal&&!document.hidden&&!game.over){accumulator+=elapsed*speed;while(accumulator>=.05){renderer.captureStep(game);game.update(.05);accumulator-=.05;if(game.event||game.over)break;}}
 if(!paused&&!modal&&!document.hidden)animationTime+=elapsed*speed;renderer.draw(game,animationTime,Math.min(1,accumulator/.05));
 voice.accept(game.calls.map(c=>({...c,text:callText(c)})),c=>game.clock-c.time<18&&game.patients.some(p=>p.id===c.patientId&&p.targetRoom===c.roomId&&['called','inside'].includes(p.state)));
 if(game.cured>lastCured){chime('cure');lastCured=game.cured;}
 if(game.event&&!modal)openModal('event');
 if(game.won&&!winShown&&!modal){winShown=true;const key=game.mode==='tutorial'?'tutorial':game.level;if(!progress.includes(key))progress.push(key);if(autosaveEnabled)save(false);openModal(game.mode==='tutorial'?'tutorial-win':'win');}
 if(game.over&&!overShown){overShown=true;openModal('over');if(autosaveEnabled)save(false);}
 if(now-lastUI>500){renderUI();lastUI=now;}
 if(autosaveEnabled&&now-lastSave>20000){save(false);lastSave=now;}
 requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
