import {Game} from './game.js';
import {Renderer} from './renderer.js';
import {ROOMS,CAST,ILLNESSES,LEVELS,PROJECTS,EVENTS,tr} from './content.js';
import {translator,detectLanguage} from './i18n.js';
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let prefs={},progress=[];try{prefs=JSON.parse(localStorage.getItem('scrubssitel-prefs')||'{}');progress=JSON.parse(localStorage.getItem('scrubssitel-progress')||'[]');if(!Array.isArray(progress))progress=[];}catch{}
let lang=['en','de'].includes(prefs.lang)?prefs.lang:detectLanguage(),t=translator(lang),game,paused=false,speed=1,panel=null,selected=null,modal=null,buildType=null,winShown=false,overShown=false,confirmAction=null,lastSave=0,autosaveEnabled=true,audio=null;
try{const s=localStorage.getItem('scrubssitel-save');game=s?Game.restore(JSON.parse(s)):new Game();}catch{game=new Game();}
const fresh=game.clock===0;
const money=n=>new Intl.NumberFormat(lang==='de'?'de-DE':'en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const label=v=>tr(v,lang);
const icons={build:'▦',staff:'♟',research:'⚗',finances:'↗',help:'?',settings:'⚙',pause:'Ⅱ',play:'▶',save:'↓',home:'⌂',close:'×'};
function btn(action,text,cls='',extra=''){return `<button type="button" class="${cls}" data-action="${action}" ${extra}>${text}</button>`;}
function iconBtn(action,icon,title){return btn(action,icon,'icon-btn',`title="${escape(title)}" aria-label="${escape(title)}"`);}
function avatar(s,size=''){return `<span class="avatar ${size}" style="--position:${[0,25,50,75,100][s.portrait]}%" role="img" aria-label="${escape(s.name)}"></span>`;}
function persistPrefs(){try{localStorage.setItem('scrubssitel-prefs',JSON.stringify(prefs));}catch{}}
function chime(type='tap'){if(!prefs.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime;for(let i=0;i<(type==='cure'?3:1);i++){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=(type==='error'?180:type==='cure'?523:440)*[1,1.25,1.5][i];g.gain.setValueAtTime(.045,now+i*.08);g.gain.exponentialRampToValueAtTime(.001,now+.14+i*.08);o.connect(g);g.connect(audio.destination);o.start(now+i*.08);o.stop(now+.16+i*.08);}}catch{}}
function notify(text,error=false){const el=$('#toast');el.textContent=text;el.classList.toggle('error',error);el.classList.add('visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.classList.remove('visible'),3200);chime(error?'error':'tap');}
function result(r,success){if(r?.error){notify(t(r.error),true);return false;}if(success)notify(success);renderUI();return true;}
function save(show=true){try{localStorage.setItem('scrubssitel-save',JSON.stringify(game.snapshot()));localStorage.setItem('scrubssitel-progress',JSON.stringify(progress));if(show)notify(t('saved'));return true;}catch{if(show)notify(t('saveFailed'),true);return false;}}
function currentLevel(){return LEVELS[game.level-1];}
function shell(){document.documentElement.lang=lang;document.title=`Scrubssitel · ${t('brandSub')}`;
 $('#app').innerHTML=`<header class="topbar"><a class="brand" href="#" aria-label="Scrubssitel"><span class="brand-mark">✚</span><span><strong>Scrubssitel<span class="brand-dot">.</span></strong><small>${t('brandSub')}</small></span></a><div class="vital-stats" id="vitals"></div><div class="top-actions">${iconBtn('save','↓',t('save'))}${iconBtn('help','?',t('help'))}${iconBtn('settings','⚙',t('settings'))}<button class="language-button" data-action="switch-language" aria-label="${t('language')}">${lang.toUpperCase()}</button></div></header>
 <nav class="workbar" aria-label="${t('yourHospital')}"><button class="hospital-name" data-action="episodes"><span class="hospital-icon">⌂</span><span><b>${lang==='de'?'Klinik Miteinander':'Common Ground Hospital'}</b><small id="episode-label"></small></span><span class="chevron">⌄</span></button><div class="management-tabs">${['staff','research','finances'].map(x=>btn('panel',`<span>${icons[x]}</span> ${t(x)}`,'tab',`data-panel="${x}"`)).join('')}</div><div class="time-controls" id="time-controls"></div></nav>
 <main class="game-shell"><aside class="shift-sidebar" id="sidebar"></aside><section class="hospital-stage" aria-label="${t('floor')}"><div class="stage-topline"><span class="live-dot"></span><span>${t('schedule')}</span><span class="stage-coordinates">${lang==='de'?'SEKTOR':'SECTOR'} 01 / 24 × 18</span></div><canvas id="hospital-canvas" tabindex="0" aria-label="${t('floor')}. ${t('buildHint')}"></canvas><div class="view-controls">${iconBtn('zoom-out','−',t('zoomOut'))}<span id="zoom-value">100%</span>${iconBtn('zoom-in','+',t('zoomIn'))}${iconBtn('center','⌖',t('resetView'))}${iconBtn('fullscreen','⛶',t('fullscreen'))}</div><div id="pause-label" class="pause-label" hidden>${t('paused')}</div><div id="stage-hint" class="stage-hint"></div><aside id="detail-panel" class="detail-panel" hidden></aside></section></main>
 <footer class="build-dock"><div class="dock-heading"><span class="dock-icon">▦</span><div><b>${t('build')}</b><small>${t('rooms')}</small></div></div><div class="room-palette" id="room-palette"></div><button class="inspect-button" data-action="inspect" title="${t('inspect')}">↖<span>${t('inspect')}</span></button></footer>
 <div id="modal-root"></div><div id="toast" class="toast" role="status" aria-live="polite"></div><input type="file" accept="application/json,.json" id="import-file" hidden>`;
 renderer=new Renderer($('#hospital-canvas'),{onBuild(type,rect){if(result(game.addRoom(type,rect),t('built'))){buildType=null;renderer.buildType=null;if(autosaveEnabled)save(false);}},onSelect(type,id){selected=type?{type,id}:null;renderer.selected=selected;panel=type?'inspect':null;renderUI();}});renderer.lang=lang;
 $('#import-file').addEventListener('change',importSave);renderUI();}
let renderer;
function renderUI(){const focused=document.activeElement;const focusAttrs=focused?.dataset?.action?Array.from(focused.attributes).filter(a=>a.name.startsWith('data-')).map(a=>`[${a.name}="${a.value}"]`).join(''):null;const active=game.patients.filter(p=>p.state!=='exit').length;
 $('#vitals').innerHTML=`<div class="vital balance"><span class="stat-icon">＄</span><div><small>${t('cash')}</small><b class="${game.cash<0?'negative':''}">${money(game.cash)}</b></div></div><div class="vital"><span class="stat-icon star">★</span><div><small>${t('reputation')}</small><b>${Math.round(game.rep)}<em>/100</em></b></div></div><div class="vital"><span class="stat-icon heart">♡</span><div><small>${t('cured')}</small><b>${game.cured}<em>${game.mode==='campaign'?' / '+currentLevel().goal:''}</em></b></div></div>`;
 $('#episode-label').textContent=game.mode==='sandbox'?t('sandbox'):`${t('level')} 0${game.level} · ${label(currentLevel().name)}`;
 $('#time-controls').innerHTML=`<span class="day-label"><span>◷</span> ${t('day')} ${String(game.day).padStart(2,'0')}</span>${btn('pause',paused?'▶':'Ⅱ',`time-button ${paused?'active':''}`,`title="${paused?t('play'):t('pause')}" aria-label="${paused?t('play'):t('pause')}"`)}${[1,2,3].map(n=>btn('speed',`${n}×`,`time-button ${speed===n?'active':''}`,`data-speed="${n}" aria-label="${n}×" aria-pressed="${speed===n}"`)).join('')}`;
 const goal=game.mode==='sandbox'?1:Math.min(1,game.cured/currentLevel().goal);const wait=game.patients.filter(p=>['waiting','queue'].includes(p.state)).length;
 $('#sidebar').innerHTML=`<div class="shift-heading"><span class="eyebrow">${game.mode==='sandbox'?t('sandbox').toUpperCase():t('level').toUpperCase()+' 0'+game.level}</span><h1>${game.mode==='sandbox'?t('morning'):label(currentLevel().name)}</h1><span class="small-badge">${game.mode==='sandbox'?'∞':game.won?'★':'☀'} ${game.mode==='sandbox'?t('free'):t('newShift')}</span></div>
 <div class="objective-card"><div class="section-label">${t('goal')} <span>⚑</span></div>${game.mode==='sandbox'?`<p>${t('free')}</p>`:`<div class="objective-row"><span>${t('cured')}</span><b>${game.cured}<small> / ${currentLevel().goal}</small></b></div><div class="progress-track"><i style="width:${goal*100}%"></i></div><div class="objective-row secondary"><span>★ ${t('reputation')}</span><b>${Math.round(game.rep)}<small> / ${currentLevel().rep}</small></b></div>`}</div>
 <div class="flow-card"><div class="section-label">${t('patientFlow')}</div><div class="flow-total"><b>${active}</b><span>${t('patients').toLowerCase()}</span><i>${wait} ${t('waiting').toLowerCase()}</i></div><div class="flow-steps">${[['diagnosis','✚'],['treatment','♡'],['departing','↗']].map(([key,icon],i)=>`<div><span>${icon}</span><b>${game.patients.filter(p=>i===0?p.stage==='diagnosis':i===1?p.stage==='treatment':p.state==='exit').length}</b><small>${t(key)}</small></div>`).join('')}</div><div class="health-line"><span>✧ ${t('cleanliness')}</span><b>${Math.round(game.cleanliness)}%</b></div><div class="thin-progress"><i style="width:${game.cleanliness}%"></i></div></div>
 <button class="cast-preview" data-action="panel" data-panel="staff"><img src="./public/assets/staff-ensemble.png" alt="${t('team')}"/><span>${t('team')} <b>↗</b></span></button>
 <div class="bea-note"><span class="note-pin"></span><div class="note-title">${t('tipTitle')}</div><p>${t(game.level===1?'tip':game.level===2?'tip2':'tip3')}</p><span class="signature">— Bea ♡</span></div>
 <div class="radio"><div class="section-label"><span class="radio-dot"></span>${t('alerts')}</div><p>${game.logs[0]?formatLog(game.logs[0]):t('noAlerts')}</p></div>`;
 $('#room-palette').innerHTML=Object.entries(ROOMS).map(([type,r])=>`<button class="room-card ${buildType===type?'selected':''}" data-action="build" data-type="${type}" ${game.available(type)?'':`disabled title="${t('level')} ${type==='therapy'?2:3}"`} aria-pressed="${buildType===type}"><span class="room-symbol" style="--room-color:${r.color}">${r.icon}</span><span class="room-card-text"><b>${label(r.name)}</b><small>${game.available(type)?money(r.cost):'⌑ '+t('level')+' '+(type==='therapy'?2:3)}</small></span></button>`).join('');
 $('#stage-hint').innerHTML=buildType?`<span class="build-mode-dot"></span><b>${label(ROOMS[buildType].name)}</b><span>${t('buildHint')}</span>${btn('inspect','×','','aria-label="'+t('cancel')+'"')}`:`<span>↖</span> ${t('selectHint')}`;
 $('#stage-hint').classList.toggle('building',!!buildType);$('#pause-label').hidden=!paused;$('#zoom-value').textContent=Math.round(renderer.zoom*100)+'%';
 document.querySelectorAll('[data-action="panel"]').forEach(b=>b.classList.toggle('active',b.dataset.panel===panel));renderPanel();if(focusAttrs&&!document.contains(focused))document.querySelector(focusAttrs)?.focus({preventScroll:true});}
function formatLog(l){let extra=l.extra;if(ROOMS[extra])extra=label(ROOMS[extra].name);if(PROJECTS.some(p=>p.id===extra))extra=label(PROJECTS.find(p=>p.id===extra).name);if(l.code==='paid')extra=money(Number(extra));return `${escape(t(l.code))}${extra?' · '+escape(extra):''}`;}
function panelHeader(title,kicker){return `<div class="panel-header"><div><small>${kicker}</small><h2>${title}</h2></div>${iconBtn('close-panel','×',t('close'))}</div>`;}
function renderPanel(){const el=$('#detail-panel');el.hidden=!panel;if(!panel)return;
 if(panel==='staff'){el.innerHTML=panelHeader(t('team'),`${game.staff.length} ${t('hired')}`)+`<div class="panel-scroll">${game.staff.map(s=>{const r=game.room(s.roomId);return `<article class="employee-card">${avatar(s)}<div class="employee-info"><b>${escape(s.name)}</b><span>${t(s.role)} · ${s.resting?t('resting'):r?label(ROOMS[r.type].name):t('idle')}</span><div class="fatigue-line"><i style="width:${s.fatigue}%;background:${s.fatigue>70?'#c28455':'#b9cb9c'}"></i></div><small>${t('fatigue')} ${Math.round(s.fatigue)}% · ${money(s.wage)} / ${t('day')}</small></div>${btn('dismiss-staff','×','dismiss-button',`data-id="${s.id}" title="${t('dismiss')}"`)}</article>`;}).join('')}<h3 class="recruit-label">${t('available')}</h3>${CAST.map(s=>`<article class="recruit-card">${avatar(s)}<div><b>${s.name}</b><span>${t(s.role)} · ${label(s.trait)}</span><small>${money(s.wage)} ${t('wage')} · ${t('skill')} ${Math.round(s.skill*100)}%</small>${btn('hire',`+ ${t('hire')} · ${money(s.hire)}`,'small-button',`data-cast="${s.id}" ${game.cash<s.hire?'disabled':''}`)}</div></article>`).join('')}</div>`;
 }else if(panel==='research'){el.innerHTML=panelHeader(t('research'),'R&D')+`<div class="panel-scroll"><p class="panel-intro">${t('noResearch')}</p>${PROJECTS.map(p=>{const done=game.completed.includes(p.id),active=game.project?.id===p.id;return `<article class="project-card"><span class="project-icon">${done?'✓':'⚗'}</span><h3>${label(p.name)}</h3><p>${label(p.desc)}</p>${active?`<div class="progress-track"><i style="width:${game.project.progress/p.time*100}%"></i></div><small>${t('researching')} · ${Math.round(game.project.progress/p.time*100)}%</small>`:btn('research',done?'✓ '+t('researched'):`${t('startResearch')} · ${money(p.cost)}`,'small-button',`data-project="${p.id}" ${done||game.project?'disabled':''}`)}</article>`;}).join('')}</div>`;
 }else if(panel==='finances'){el.innerHTML=panelHeader(t('finances'),t('cashFlow'))+`<div class="panel-scroll"><div class="finance-balance"><small>${t('cash')}</small><b>${money(game.cash)}</b></div><h3>${t('allTime')}</h3>${[[t('income'),game.income],[t('expenses'),-game.expenses],[t('construction'),-game.construction],[t('profit'),game.income-game.expenses-game.construction]].map(([k,v])=>`<div class="finance-row"><span>${k}</span><b class="${v<0?'negative':'positive'}">${money(v)}</b></div>`).join('')}<div class="daily-cost"><span>${t('dailyCost')}</span><b>${money(game.dailyCost())}</b></div><p class="panel-intro">${t('financeDesc')}</p>${game.ledger.map(l=>`<div class="finance-row"><span>${t('day')} ${l.day}</span><b>−${money(l.cost)}</b></div>`).join('')}</div>`;
 }else if(panel==='inspect'){if(selected?.type==='room'){const r=game.room(selected.id);if(!r){panel=null;el.hidden=true;return;}const type=ROOMS[r.type],s=game.staff.find(s=>s.id===r.staffId);el.innerHTML=panelHeader(label(type.name),t('roomDetails'))+`<div class="panel-scroll"><div class="room-detail-symbol" style="background:${type.color}">${type.icon}</div><p class="panel-intro">${label(type.desc)}</p><div class="room-status">${s?avatar(s):'<span>♟</span>'}<div><b>${s?escape(s.name):t('uncovered')}</b><small>${s?(s.resting?t('resting'):r.patientId?t('working'):t('idle')):t('noStaff')}</small></div></div><div class="detail-grid">${[[t('levelWord'),r.level+'/3'],[t('queue'),game.queue(r)],[t('condition'),Math.round(r.condition)+'%'],[t('success'),type.time?Math.round(game.success(r)*100)+'%':'—']].map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('')}</div>${r.level<3?btn('upgrade',`${t('upgrade')} · ${money(Math.round(type.cost*.65*r.level))}`,'primary full',`data-id="${r.id}"`):`<p>${t('maxLevel')}</p>`}${btn('sell',`${t('sell')} · +${money(Math.round(type.cost*.5))}`,'text-button full',`data-id="${r.id}"`)}</div>`;
 }else if(selected?.type==='patient'){const p=game.patients.find(p=>p.id===selected.id);if(!p){panel=null;el.hidden=true;selected=null;return;}const illness=ILLNESSES.find(i=>i.id===p.illness);el.innerHTML=panelHeader(escape(p.name),t('patientDetails'))+`<div class="panel-scroll"><div class="patient-icon" style="background:${illness.color}">♡</div><h3>${label(illness.name)}</h3><p class="panel-intro">${p.stage==='exit'?t('departing'):t('waitingFor')+' '+label(ROOMS[game.need(p)].name)}</p><div class="objective-row"><span>${t('health')}</span><b>${Math.round(p.patience)}%</b></div><div class="progress-track"><i style="width:${p.patience}%"></i></div><div class="finance-row"><span>${t('fee')}</span><b>${money(illness.fee)}</b></div></div>`;}else{panel=null;el.hidden=true;}}
}
let previousFocus=null;
function openModal(type,extra){previousFocus=document.activeElement;modal={type,extra};renderModal();}
function closeModal(){modal=null;$('#modal-root').innerHTML='';document.querySelector('.topbar').inert=false;document.querySelector('.workbar').inert=false;document.querySelector('.game-shell').inert=false;document.querySelector('.build-dock').inert=false;previousFocus?.focus();}
function renderModal(){if(!modal)return;let html='',wide=false;const type=modal.type;
 if(type==='welcome'){wide=true;html=`<div class="welcome-art"><img src="./public/assets/staff-ensemble.png" alt="${t('team')}"/><span class="art-stamp">COMMON<br>GROUND<br><b>✚</b></span></div><div class="welcome-copy"><span class="eyebrow">SCRUBSSITEL · ${t('level')} 01</span><h2>${t('guideTitle')}</h2><p>${t('guideSubtitle')}</p><div class="welcome-brief"><span>⚑</span><p>${label(currentLevel().desc)}</p></div><div class="modal-actions">${btn('close-modal',t('start')+' →','primary')}${btn('help',t('help'),'secondary')}</div><div class="welcome-foot">DE / EN <span>·</span> ${t('autoSave')}</div></div>`;
 }else if(type==='help'){wide=true;html=`<div class="modal-body"><span class="eyebrow">${lang==='de'?'DIE EINWEISUNG, DIE EINE E-MAIL HÄTTE SEIN KÖNNEN':'THE ORIENTATION THAT COULD HAVE BEEN AN EMAIL'}</span><h2>${t('help')}</h2><p class="modal-subtitle">${t('guideSubtitle')}</p><div class="guide-grid">${[1,2,3,4,5].map(i=>`<div><span class="guide-number">0${i}</span><h3>${t('guide'+i)}</h3><p>${t('guide'+i+'Text')}</p></div>`).join('')}</div><p class="keyboard-guide">${t('controls')}</p>${btn('close-modal',t('gotIt')+' →','primary')}</div>`;
 }else if(type==='episodes'){wide=true;html=`<div class="modal-body"><span class="eyebrow">SCRUBSSITEL</span><h2>${t('selectEpisode')}</h2><div class="episode-grid">${LEVELS.map(l=>{const locked=l.id>1&&!progress.includes(l.id-1);return `<article class="episode-card ${locked?'locked':''}"><span class="episode-number">0${l.id}</span><span class="eyebrow">${t('level')} ${l.id} ${progress.includes(l.id)?'★':''}</span><h3>${label(l.name)}</h3><p>${label(l.desc)}</p>${btn('new-game',locked?'⌑ '+t('locked'):t('start')+' →','small-button',`data-level="${l.id}" data-mode="campaign" ${locked?'disabled':''}`)}</article>`;}).join('')}</div><div class="sandbox-card"><div><h3>∞ ${t('sandbox')}</h3><p>${t('sandboxDesc')}</p></div>${btn('new-game',t('start')+' →','primary','data-mode="sandbox" data-level="1"')}</div></div>`;
 }else if(type==='settings'){html=`<div class="modal-body"><span class="eyebrow">SCRUBSSITEL</span><h2>${t('settings')}</h2><label class="settings-row">${t('language')}<select id="language-select"><option value="auto" ${!prefs.lang||prefs.lang==='auto'?'selected':''}>${t('auto')}</option><option value="en" ${prefs.lang==='en'?'selected':''}>English</option><option value="de" ${prefs.lang==='de'?'selected':''}>Deutsch</option></select></label><div class="settings-row"><span>${t('sound')}</span>${btn('sound',prefs.sound?t('on'):t('off'),'toggle '+(prefs.sound?'enabled':''),'aria-pressed="'+!!prefs.sound+'"')}</div><p class="panel-intro">${t('autoSave')}</p><div class="save-buttons">${btn('export','↓ '+t('export'),'secondary')}${btn('import','↑ '+t('import'),'secondary')}</div>${btn('episodes',t('newGame'),'text-button full')}${btn('delete-save',t('deleteSave'),'text-button full danger')}<p class="credits">${t('credits')}</p><a class="source-link" href="https://github.com/MarcelWeissgerberIT/scrubssitel" target="_blank" rel="noopener">GitHub ↗</a></div>`;
 }else if(type==='event'){const ev=EVENTS.find(e=>e.id===game.event);if(!ev){closeModal();return;}html=`<div class="modal-body event-body"><span class="eyebrow">${t('event')}</span><div class="event-emoji">${{coffee:'☕',review:'★',grant:'✉',rush:'⚡'}[ev.id]}</div><h2>${label(ev.name)}</h2><p>${label(ev.text)}</p><div class="event-choices">${ev.choices.map((c,i)=>btn('event-choice',label(c.label),'secondary',`data-choice="${i}" ${c.cost>0&&game.cash<c.cost?'disabled':''}`)).join('')}</div></div>`;
 }else if(type==='win'||type==='over'){html=`<div class="modal-body win-body"><span class="win-icon">${type==='win'?'★':'☂'}</span><span class="eyebrow">${t('level')} 0${game.level}</span><h2>${t(type==='win'?'win':'gameOver')}</h2><p>${t(type==='win'?'winText':'gameOverText')}</p><div class="win-stats"><span><b>${game.cured}</b>${t('cured')}</span><span><b>${Math.round(game.rep)}</b>${t('reputation')}</span><span><b>${money(game.cash)}</b>${t('cash')}</span></div>${type==='win'?(game.level<3?btn('next',t('nextEpisode')+' →','primary full'):`<p>${t('completedCampaign')}</p>`)+btn('close-modal',t('keepPlaying'),'text-button full'):btn('retry',t('retry'),'primary full')}</div>`;
 }else if(type==='confirm'){html=`<div class="modal-body"><h2>${t(modal.extra.title)}</h2><p>${t(modal.extra.text)}</p><div class="modal-actions">${btn('confirm',t('yes'),'primary')}${btn('close-modal',t('cancel'),'secondary')}</div></div>`;}
 $('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${wide?'wide':''} ${type==='welcome'?'welcome-modal':''}" role="dialog" aria-modal="true" aria-label="${escape(type==='welcome'?t('guideTitle'):type==='event'?t('event'):t(type==='episodes'?'selectEpisode':type==='over'?'gameOver':type))}">${!['welcome','event','over','win','confirm'].includes(type)?iconBtn('close-modal','×',t('close')):''}${html}</section></div>`;
 for(const selector of ['.topbar','.workbar','.game-shell','.build-dock'])$(selector).inert=true;
 requestAnimationFrame(()=>$('#modal-root button:not(:disabled)')?.focus());
 $('#language-select')?.addEventListener('change',e=>{prefs.lang=e.target.value;persistPrefs();changeLanguage(prefs.lang==='auto'?detectLanguage():prefs.lang);});
}
function confirm(title,text,action){confirmAction=action;openModal('confirm',{title,text});}
function newGame(mode,level){game=new Game({mode,level});lastCured=game.cured;paused=false;speed=1;selected=null;panel=null;buildType=null;winShown=false;overShown=false;renderer.selected=null;renderer.buildType=null;renderer.reset();autosaveEnabled=true;closeModal();save(false);renderUI();}
function changeLanguage(next){lang=next;t=translator(lang);const oldZoom=renderer.zoom,oldPan=renderer.pan;const oldModal=modal;shell();renderer.zoom=oldZoom;renderer.pan=oldPan;renderer.selected=selected;renderer.buildType=buildType;modal=oldModal;if(modal)renderModal();}
async function importSave(e){try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Too large');const data=JSON.parse(await file.text());const restored=Game.restore(data.game||data);game=restored;lastCured=game.cured;if(data.progress&&Array.isArray(data.progress))progress=data.progress.filter(x=>[1,2,3].includes(x));selected=null;panel=null;renderer.selected=null;buildType=null;renderer.buildType=null;paused=true;winShown=game.won;overShown=false;autosaveEnabled=true;closeModal();save(false);renderUI();notify(t('imported'));}catch{notify(t('badSave'),true);}e.target.value='';}
function exportSave(){const blob=new Blob([JSON.stringify({game:game.snapshot(),progress},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`scrubssitel-day-${game.day}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('#app').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 switch(a){case 'pause':paused=!paused;renderUI();break;case 'speed':speed=+b.dataset.speed;paused=false;renderUI();break;case 'save':autosaveEnabled=true;save();break;case 'help':openModal('help');break;case 'settings':openModal('settings');break;case 'episodes':openModal('episodes');break;case 'close-modal':if(!game.event&&!game.over)closeModal();break;case 'switch-language':prefs.lang=lang==='en'?'de':'en';persistPrefs();changeLanguage(prefs.lang);break;case 'panel':panel=panel===b.dataset.panel?null:b.dataset.panel;renderUI();break;case 'close-panel':panel=null;selected=null;renderer.selected=null;renderUI();break;
 case 'build':buildType=buildType===b.dataset.type?null:b.dataset.type;renderer.buildType=buildType;panel=null;selected=null;renderer.selected=null;renderUI();break;case 'inspect':buildType=null;renderer.buildType=null;renderer.drag=null;renderUI();break;case 'hire':result(game.hire(b.dataset.cast),t('hireDone'));break;case 'dismiss-staff':confirm('dismiss','dismissText',()=>result(game.dismiss(+b.dataset.id)));break;case 'upgrade':result(game.upgrade(+b.dataset.id),t('upgraded'));break;case 'sell':confirm('confirmSell','confirmSellText',()=>{if(result(game.sell(+b.dataset.id))){selected=null;panel=null;renderer.selected=null;}});break;case 'research':result(game.startResearch(b.dataset.project));break;
 case 'zoom-in':renderer.setZoom(renderer.zoom+.15);renderUI();break;case 'zoom-out':renderer.setZoom(renderer.zoom-.15);renderUI();break;case 'center':renderer.reset();renderUI();break;case 'fullscreen':if(!document.fullscreenElement){document.documentElement.requestFullscreen?.().catch(()=>{});}else document.exitFullscreen?.();break;
 case 'new-game':{const mode=b.dataset.mode,level=+b.dataset.level;confirm('confirmNew','confirmNewText',()=>newGame(mode,level));break;}case 'confirm':{const action=confirmAction;closeModal();action?.();renderUI();break;}case 'next':newGame('campaign',Math.min(3,game.level+1));break;case 'retry':newGame(game.mode,game.level);break;
 case 'sound':prefs.sound=!prefs.sound;persistPrefs();chime();renderModal();break;case 'export':exportSave();break;case 'import':$('#import-file').click();break;case 'delete-save':confirm('deleteSave','deleteSaveText',()=>{try{localStorage.removeItem('scrubssitel-save');localStorage.removeItem('scrubssitel-progress');progress=[];autosaveEnabled=false;notify(t('deleted'));}catch{notify(t('saveFailed'),true);}});break;
 case 'event-choice':if(result(game.resolveEvent(+b.dataset.choice))){closeModal();if(autosaveEnabled)save(false);}break;
 }});
document.addEventListener('keydown',e=>{if(modal){if(e.key==='Tab'){const items=[...document.querySelectorAll('#modal-root button:not(:disabled), #modal-root select, #modal-root a')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}if(e.key==='Escape'&&!['event','over','win','welcome'].includes(modal.type))closeModal();return;}if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement?.tagName)&&e.key!=='Escape')return;if(e.code==='Space'){e.preventDefault();paused=!paused;renderUI();}if(['1','2','3'].includes(e.key)){speed=+e.key;paused=false;renderUI();}if(e.key.toLowerCase()==='b'){buildType=buildType?null:'gp';renderer.buildType=buildType;renderer.canvas.focus();renderUI();}if(e.key==='Escape'){buildType=null;renderer.buildType=null;renderer.drag=null;panel=null;renderUI();}});
window.addEventListener('beforeunload',()=>{if(autosaveEnabled)save(false);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&autosaveEnabled)save(false);});
shell();if(fresh)openModal('welcome');else winShown=game.won;
let last=performance.now(),accumulator=0,lastUI=0,lastCured=game.cured;
function frame(now){const elapsed=Math.min((now-last)/1000,.25);last=now;
 if(!paused&&!modal&&!document.hidden&&!game.over){accumulator+=elapsed*speed;while(accumulator>=.05){game.update(.05);accumulator-=.05;if(game.event||game.over)break;}}
 renderer.draw(game,now/1000);
 if(game.cured>lastCured){chime('cure');lastCured=game.cured;}
 if(game.event&&!modal)openModal('event');
 if(game.won&&!winShown&&!modal){winShown=true;if(!progress.includes(game.level))progress.push(game.level);if(autosaveEnabled)save(false);openModal('win');}
 if(game.over&&!overShown){overShown=true;openModal('over');if(autosaveEnabled)save(false);}
 if(now-lastUI>500){renderUI();lastUI=now;}
 if(autosaveEnabled&&now-lastSave>20000){save(false);lastSave=now;}
 requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
