// One registry drives furniture, seat reservations, hit targets and explanations.
export const OBJECT_INFO={
 door:[['Quiet please door','Bitte-leise-Tür'],['Opens automatically for arrivals, called patients and staff. Holding it open never changes the waiting order.','Öffnet für Ankommende, aufgerufene Patienten und Personal. Offenhalten ändert niemals die Warteliste.']],
 chair:[['Cloud cushion chair','Wolkenpolster-Stuhl'],['One reserved seat. Sitting slows patience loss. The cushion has heard everything.','Ein reservierbarer Sitzplatz. Sitzen senkt den Geduldsverlust. Das Kissen hat schon alles gehört.']],
 sofa:[['The patience sofa','Geduldssofa'],['Cushioned seats, no wrestling over the remote. In waiting rooms they reduce patience loss; the staff room helps staff recover.','Polsterplätze, kein Streit um die Fernbedienung. Im Wartebereich senken sie den Geduldsverlust; im Personalraum erholen sich Mitarbeiter.']],
 toys:[['Tiny trouble corner','Mini-Chaos-Ecke'],['Blocks, a toy duck and a picture book. Children seated in this waiting room lose 35% less patience. No batteries. Miracles happen.','Bauklötze, Spielente und Bilderbuch. Sitzende Kinder verlieren hier 35 % weniger Geduld. Ohne Batterien. Es gibt Wunder.']],
 books:[['Very old news','Nachrichten von vorgestern'],['A little reading table. The magazines are decorative; nobody has solved the crossword since 1998.','Ein Lesetisch. Die Hefte sind Dekoration; das Kreuzworträtsel ist seit 1998 ungelöst.']],
 plant:[['Dr. Leaf','Dr. Blatt'],['Decorative greenery. Excellent listener, still no medical license.','Dekoratives Grün. Hervorragender Zuhörer, weiterhin ohne Approbation.']],
 counter:[['Check-in counter','Anmeldetheke'],['A complete reception workplace with chair, monitor and bell. Keep both the staff approach and patient side accessible. Registration is free.','Ein vollständiger Empfangsplatz mit Stuhl, Monitor und Klingel. Personalzugang und Patientenseite müssen erreichbar bleiben. Die Anmeldung ist kostenlos.']],
 monitor:[['Queue commander','Wartelisten-Wächter'],['The registration list. Doctors call the oldest waiting appointment as soon as a room and its clinician are ready.','Die Anmeldeliste. Sobald Raum und Behandler frei sind, wird der älteste wartende Termin aufgerufen.']],
 bell:[['Ding, not a diagnosis','Ding ist keine Diagnose'],['The reception bell. Please ring with your finger, not your entire personality. Decorative; hiring reception staff makes registration work.','Die Empfangsglocke. Bitte mit dem Finger klingeln, nicht mit der gesamten Persönlichkeit. Dekoration; für die Anmeldung braucht es Personal.']],
 stool:[['Spin doctor stool','Dreh-und-Angel-Stuhl'],['A seat for staff. Staff recover fatigue during breaks in the staff room.','Ein Personalsitz. Müdigkeit erholt sich in Pausen im Personalraum.']],
 poster:[['Doctor Duck’s wall chart','Doktor Entes Wandbild'],['A cheerful reminder: wash your hands, then believe in the duck. Decorative clinic art.','Eine freundliche Erinnerung: Hände waschen, dann an die Ente glauben. Dekoration für die Klinik.']],
 clock:[['The appointment optimist','Der Termin-Optimist'],['The clinic clock runs while the hospital is open. It has never admitted to being behind schedule.','Die Klinikuhr läuft während der Öffnung. Sie behauptet weiterhin, im Zeitplan zu sein.']],
 gp:[['Quack-o-scan','Quak-o-skop'],['The doctor diagnoses imaginary ailments here. A spinning duck is reassuringly scientific. Upgrading the room speeds up consultations.','Hier diagnostiziert der Arzt Fantasiekrankheiten. Eine rotierende Ente wirkt überzeugend wissenschaftlich. Raumausbau beschleunigt die Sprechstunde.']],
 pharmacy:[['Decaf 3000','Entkoffeinator 3000'],['Nurses treat caffeine jitters and clipboard fever. Upgrade the room for faster treatment and a better cure chance.','Pflegekräfte behandeln Koffeinzittern und Klemmbrettfieber. Raumausbau verbessert Tempo und Heilungschance.']],
 therapy:[['Dream steamer','Traumpuster'],['A doctor treats daydreams that escaped their owner. Room upgrades improve treatment.','Ein Arzt behandelt Tagträume, die ihrem Besitzer entwischt sind. Raumausbau verbessert die Behandlung.']],
 surgery:[['Smile press','Grinsebügler'],['A surgeon irons out fictional beauty disasters. No real medical advice, just extremely confident machinery.','Eine Chirurgin bügelt erfundene Schönheitskatastrophen aus. Keine echte Medizin, nur sehr selbstbewusste Technik.']],
 lab:[['Duck science station','Entenforschungsstation'],['Assign a doctor and fund a research project. Rubber duck peer review is surprisingly strict.','Arzt einstellen und Forschungsprojekt finanzieren. Die Gummienten-Begutachtung ist überraschend streng.']],
 coffee:[['Staff fuel station','Personal-Tankstelle'],['The staff room speeds recovery during breaks. This decorative coffee machine takes morale very seriously.','Der Personalraum beschleunigt die Erholung in Pausen. Diese dekorative Kaffeemaschine nimmt die Stimmung sehr ernst.']],
 toilet:[['Porcelain throne','Porzellanthron'],['A restroom reduces patience loss throughout the clinic. Please do not schedule a board meeting here.','Toiletten senken den Geduldsverlust in der Klinik. Bitte keine Vorstandssitzung hier abhalten.']],
 'toilet-cubicle':[['Private toilet cubicle','Blickdichte WC-Kabine'],['A complete toilet with opaque walls and its own door. Keep the entrance clear. A furnished restroom reduces patience loss throughout the clinic.','Kompletter Toilettenplatz mit blickdichten Wänden und eigener Tür. Den Eingang freihalten. Ein eingerichteter Toilettenraum senkt den Geduldsverlust in der Klinik.']],
 'cubicle-back':[['Cubicle back panel','WC-Kabinenrückwand'],['An opaque back panel belonging to the complete toilet cubicle. Move or remove the cubicle as one furniture set.','Eine blickdichte Rückwand der vollständigen WC-Kabine. Die gesamte Kabine lässt sich als ein Möbelstück verschieben oder entfernen.']],
 'cubicle-side':[['Cubicle partition','WC-Kabinentrennwand'],['An opaque partition belonging to the complete toilet cubicle. The panel blocks movement and screens the toilet from neighboring fixtures.','Eine blickdichte Trennwand der vollständigen WC-Kabine. Sie blockiert Laufwege und schirmt das WC zur benachbarten Einrichtung ab.']],
 'cubicle-door':[['Cubicle privacy door','WC-Kabinentür'],['The door of a complete toilet cubicle keeps the porcelain throne private. Leave a clear approach in front of it.','Die Tür einer vollständigen WC-Kabine schützt die Privatsphäre am Porzellanthron. Den Zugang davor freihalten.']],
 sink:[['Bubble basin','Blubberbecken'],['Required in restrooms, optional in treatment rooms. Leave a clear approach for handwashing. The soap has an excellent attendance record.','Pflichtausstattung der Toilette, optional in Behandlungsräumen. Der Zugang zum Händewaschen muss frei bleiben. Die Seife glänzt mit Anwesenheit.']],
 cabinet:[['Extremely organized cupboard','Höchst organisierter Schrank'],['Decorative storage for supplies. The drawer marked miscellaneous contains everything.','Dekorativer Vorratsschrank. In der Schublade Sonstiges liegt alles.']]
};

Object.assign(OBJECT_INFO,{
 'counter-round':[['Round welcome desk','Runder Empfangstresen'],['A curved oak reception workplace with chair, computer and bell. An alternative to the classic desk.','Ein geschwungener Empfangsplatz aus Holz mit Stuhl, Computer und Glocke. Alternative zum klassischen Tresen.']],
 'counter-modern':[['Bright welcome desk','Heller Empfangstresen'],['A clean, modern reception workplace. Same registration service, a different look for your practice.','Ein heller, moderner Empfangsplatz. Gleiche Anmeldung, ein anderer Look für deine Praxis.']],
 'pharmacy-counter':[['Dispensing counter','Apothekentresen'],['A staffed pharmacy treatment station with a medicine shelf. Replaces the Decaf 3000; both sides must stay accessible.','Ein Behandlungsplatz für die Pflegekraft mit Medikamentenregal. Ersetzt den Entkoffeinator; beide Seiten müssen erreichbar bleiben.']],
 'writing-desk':[['Paperwork desk','Schreibtisch'],['A wooden desk for the paperwork that mysteriously multiplies overnight. Decorative; the room’s treatment station remains required.','Holztisch für Papierkram, der sich nachts geheimnisvoll vermehrt. Dekoration; der Behandlungsplatz bleibt erforderlich.']],
 'round-table':[['Round discussion table','Runder Besprechungstisch'],['A round table for meetings that should have been a postcard. Decorative furniture for shared rooms.','Ein runder Tisch für Meetings, die eine Postkarte hätten sein können. Dekoration für Gemeinschaftsräume.']],
 'medicine-rack':[['Medicine shelf','Medikamentenregal'],['Colorful boxes, ointments and extremely confident labels. Decorative storage; it does not replace a staffed treatment station.','Bunte Packungen, Salben und sehr selbstbewusste Etiketten. Dekorative Aufbewahrung; ersetzt keinen besetzten Behandlungsplatz.']],
 'gum-machine':[['Bubble trouble dispenser','Kaugummiautomat'],['Waiting patients can buy a gumball for $3; each sale costs $1 in stock. Also reduces seated patience loss here by 5%. The bubble is complimentary. Keep the front accessible.','Wartende können für $3 einen Kaugummi kaufen; Wareneinsatz je Verkauf: $1. Senkt hier außerdem den Geduldsverlust im Sitzen um 5 %. Die Blase ist gratis. Vorderseite freihalten.']],
 'snack-machine':[['Emergency snack supply','Notfall-Knusperautomat'],['Waiting patients can buy a snack for $8; each sale costs $3 in stock. Spirals turn and a packet drops only during a purchase. For snack emergencies, not medical ones. Keep the front accessible.','Wartende können für $8 einen Snack kaufen; Wareneinsatz je Verkauf: $3. Nur beim Kauf drehen sich die Spiralen und eine Tüte fällt heraus. Für Knuspernotfälle. Vorderseite freihalten.']],
 'drink-machine':[['Sip, sip, hooray','Schluck-und-jubel-Automat'],['Waiting patients can buy a drink for $6; each sale costs $2 in stock. A chilled bottle slides into the collection hatch during a purchase. Hydration with excellent accounting. Keep the front accessible.','Wartende können für $6 ein Getränk kaufen; Wareneinsatz je Verkauf: $2. Beim Kauf gleitet eine kühle Flasche ins Ausgabefach. Erfrischung mit ordentlicher Buchführung. Vorderseite freihalten.']],
 'newspaper-rack':[['Yesterday’s headlines','Zeitungsständer'],['Yesterday’s news is today’s distraction. In a waiting area, seated patients lose 5% less patience. One bonus per type; amenities combine up to 15%.','Nachrichten von gestern lenken heute noch ab. In einem Wartebereich verlieren sitzende Patienten 5 % weniger Geduld. Ein Bonus je Typ; Extras zusammen höchstens 15 %.']],
 'water-dispenser':[['Water cooler','Wasserspender'],['Water and the latest clinic gossip. In a waiting area, seated patients lose 5% less patience. One bonus per type; amenities combine up to 15%.','Wasser und der neueste Praxis-Tratsch. In einem Wartebereich verlieren sitzende Patienten 5 % weniger Geduld. Ein Bonus je Typ; Extras zusammen höchstens 15 %.']],
 'coat-rack':[['Coat stand','Garderobenständer'],['A decorative home for coats, scarves and one suspicious umbrella. The umbrella is not a doctor.','Ein dekorativer Platz für Jacken, Schals und einen verdächtigen Schirm. Der Schirm ist kein Arzt.']],
 sanitizer:[['Hand sanitizer stand','Desinfektionsspender'],['A decorative reminder for clean hands. Your janitor still takes care of clinic cleanliness.','Ein dekorativer Hinweis auf saubere Hände. Für die Sauberkeit der Klinik ist weiterhin die Haustechnik zuständig.']],
 'privacy-screen':[['Fabric privacy screen','Stoff-Trennwand'],['Three fabric panels for a little privacy. Staff and patients walk around the screen; keep doors and workstations accessible.','Drei Stoffpaneele für etwas Privatsphäre. Personal und Patienten gehen um die Trennwand herum; Türen und Arbeitsplätze müssen erreichbar bleiben.']],
 'glass-partition':[['Frosted glass divider','Glas-Trennwand'],['A freestanding frosted glass divider. Separates floor space without becoming a new room; leave a clear route around it.','Eine freistehende Trennwand aus Milchglas. Teilt die Fläche, ohne einen neuen Raum zu bilden; lass einen freien Weg darum herum.']],
 'treatment-trolley':[['Treatment trolley','Behandlungswagen'],['Cotton, bottles and a very orderly tray. Additional room furniture; the staffed treatment station is still required.','Watte, Fläschchen und ein auffällig ordentliches Tablett. Zusätzliche Raumausstattung; der besetzte Behandlungsplatz bleibt erforderlich.']],
 'waste-bin':[['Pedal bin','Tretmülleimer'],['A small pedal bin with an optimistic expression. Decorative; clinic cleanliness still depends on your janitor.','Ein kleiner Tretmülleimer mit optimistischem Gesicht. Dekoration; die Sauberkeit der Klinik bleibt Aufgabe der Haustechnik.']],
 'examination-couch':[['Examination couch','Untersuchungsliege'],['A cushioned examination couch with a fresh paper roll. Additional furniture, not a replacement for the room’s treatment station.','Eine gepolsterte Untersuchungsliege mit frischer Papierrolle. Zusätzliche Einrichtung, kein Ersatz für den Behandlungsplatz des Raums.']]
});

// Positions in furniture records are local physical floor coordinates. Actors
// use the same world with a -.5 offset on each axis (the renderer adds it back).
const ALL=['reception','gp','pharmacy','therapy','surgery','lab','waiting','lounge','toilet'];
const solid=(w,h)=>[{part:'body',x:0,y:0,w,h}];
const device=(kind,cost)=>({rooms:[kind],w:1.25,h:1.25,z:1.7,cost,solids:solid(1.25,1.25),ports:[{kind:'work',x:1.75,y:.25,lookYaw:-Math.PI/2},...(kind==='lab'?[]:[{kind:'patient',x:1.75,y:1,lookYaw:-Math.PI/2}])]});
export const FURNITURE={
 counter:{rooms:['reception'],w:1.5,h:1.5,z:.57,cost:450,solids:[{part:'counter',x:0,y:.75,w:1.5,h:.75},{part:'stool',x:.5,y:0,w:.5,h:.5}],ports:[{kind:'work',x:.75,y:.25,lookYaw:0,seat:true,solidPart:'stool',approach:{x:.25,y:.25}},{kind:'patient',x:.75,y:1.75,lookYaw:Math.PI}],parts:[{kind:'stool',part:'stool',x:.5,y:0,w:.5,h:.5,z:.76,seatHeight:.32},{kind:'counter',part:'counter',x:0,y:.75,w:1.5,h:.75,z:.57},{kind:'monitor',part:'monitor',x:.85,y:1.0,w:.4,h:.2,z:.91},{kind:'bell',part:'bell',x:.15,y:1,w:.3,h:.3,z:.72}]},
 gp:device('gp',600),pharmacy:device('pharmacy',750),therapy:device('therapy',1100),surgery:device('surgery',1600),lab:device('lab',1000),
 chair:{rooms:['waiting','lounge'],w:.75,h:.75,z:.7,cost:80,solids:solid(.75,.75),ports:[{kind:'seat',x:.375,y:.375,lookYaw:0,seat:true,solidPart:'body',approach:{x:.375,y:1}}]},
 sofa:{rooms:['waiting','lounge'],w:1.75,h:.75,z:.7,cost:180,solids:solid(1.75,.75),ports:[{kind:'seat',x:.4375,y:.375,lookYaw:0,seat:true,solidPart:'body',approach:{x:.4375,y:1}},{kind:'seat',x:1.3125,y:.375,lookYaw:0,seat:true,solidPart:'body',approach:{x:1.3125,y:1}}]},
 toilet:{rooms:['toilet'],w:.75,h:1,z:.75,cost:180,solids:solid(.75,1),ports:[{kind:'use',x:.375,y:1.25,lookYaw:Math.PI}]},
 'toilet-cubicle':{rooms:['toilet'],w:1.5,h:2,z:1.18,cost:450,fulfills:['toilet'],
  solids:[{part:'toilet',x:.375,y:.2,w:.75,h:1},{part:'back',x:0,y:0,w:1.5,h:.1},{part:'left',x:0,y:.1,w:.1,h:1.9},{part:'right',x:1.4,y:.1,w:.1,h:1.9},{part:'door',x:.1,y:1.9,w:1.3,h:.1}],
  ports:[{kind:'use',x:.75,y:2.25,lookYaw:Math.PI}],
  parts:[{kind:'toilet',part:'toilet',x:.375,y:.2,w:.75,h:1,z:.75},{kind:'cubicle-back',part:'back',x:0,y:0,w:1.5,h:.1,z:1.18,base:.1},{kind:'cubicle-side',part:'left',x:0,y:.1,w:.1,h:1.9,z:1.18,base:.1},{kind:'cubicle-side',part:'right',x:1.4,y:.1,w:.1,h:1.9,z:1.18,base:.1},{kind:'cubicle-door',part:'door',x:.1,y:1.9,w:1.3,h:.1,z:1.18,base:.1}]},
 sink:{rooms:['toilet','gp','pharmacy','therapy','surgery','lab'],w:.75,h:.5,z:.72,cost:100,solids:solid(.75,.5),ports:[{kind:'use',x:.375,y:.75,lookYaw:Math.PI}]},
 coffee:{rooms:['lounge'],w:.75,h:.75,z:1.1,cost:140,solids:solid(.75,.75),ports:[{kind:'use',x:.375,y:1,lookYaw:Math.PI}]},
 toys:{rooms:['waiting'],w:1,h:.5,z:.45,cost:90,solids:solid(1,.5),ports:[]},
 books:{rooms:['waiting','lounge'],w:.75,h:.5,z:.4,cost:60,solids:solid(.75,.5),ports:[]},
 plant:{rooms:ALL,w:.5,h:.5,z:.85,cost:45,solids:solid(.5,.5),ports:[]},
 cabinet:{rooms:ALL,w:.75,h:.5,z:.85,cost:100,solids:solid(.75,.5),ports:[]},
 poster:{rooms:ALL,w:.5,h:.25,z:1.13,cost:25,wall:true,solids:[],ports:[]},
 clock:{rooms:ALL,w:.25,h:.25,z:1.13,cost:30,wall:true,solids:[],ports:[]}
};
for(const [kind,design,cost] of [['counter-round','round',650],['counter-modern','modern',550]]){
 FURNITURE[kind]={...FURNITURE.counter,cost,fulfills:['counter'],parts:FURNITURE.counter.parts.map(part=>({...part,...(part.kind==='counter'?{design}:{})}))};
}
Object.assign(FURNITURE,{
 'pharmacy-counter':{rooms:['pharmacy'],w:2,h:1.5,z:1.1,cost:850,fulfills:['pharmacy'],solids:[{part:'counter',x:0,y:.75,w:2,h:.75},{part:'shelf',x:0,y:0,w:.5,h:.5}],ports:[{kind:'work',x:1,y:.25,lookYaw:0},{kind:'patient',x:1,y:1.75,lookYaw:Math.PI}],parts:[{kind:'counter',design:'dispensary',part:'counter',x:0,y:.75,w:2,h:.75,z:.57},{kind:'medicine-rack',part:'shelf',x:0,y:0,w:.5,h:.5,z:1.1}]},
 'writing-desk':{rooms:['reception','gp','pharmacy','therapy','surgery','lab'],w:1.5,h:.75,z:.65,cost:240,solids:solid(1.5,.75),ports:[{kind:'use',x:.75,y:1,lookYaw:Math.PI}]},
 'round-table':{rooms:['waiting','lounge','reception','therapy'],w:1,h:1,z:.6,cost:160,solids:solid(1,1),ports:[]},
 'medicine-rack':{rooms:['pharmacy','gp','surgery','lab'],w:.75,h:.5,z:1.1,cost:180,solids:solid(.75,.5),ports:[{kind:'use',x:.375,y:.75,lookYaw:Math.PI}]},
 'gum-machine':{rooms:['waiting','reception','lounge'],w:.5,h:.5,z:1.15,cost:130,comfort:.05,vending:{price:3,cost:1,duration:2.4},solids:solid(.5,.5),ports:[{kind:'use',x:.25,y:.75,lookYaw:Math.PI}]},
 'snack-machine':{rooms:['waiting','reception','lounge'],w:.75,h:.75,z:1.4,cost:380,vending:{price:8,cost:3,duration:2.4},solids:solid(.75,.75),ports:[{kind:'use',x:.375,y:1,lookYaw:Math.PI}]},
 'drink-machine':{rooms:['waiting','reception','lounge'],w:.75,h:.75,z:1.4,cost:420,vending:{price:6,cost:2,duration:2.4},solids:solid(.75,.75),ports:[{kind:'use',x:.375,y:1,lookYaw:Math.PI}]},
 'newspaper-rack':{rooms:['waiting','reception','lounge'],w:.5,h:.5,z:.8,cost:95,comfort:.05,solids:solid(.5,.5),ports:[{kind:'use',x:.25,y:.75,lookYaw:Math.PI}]},
 'water-dispenser':{rooms:ALL,w:.5,h:.5,z:1.1,cost:160,comfort:.05,solids:solid(.5,.5),ports:[{kind:'use',x:.25,y:.75,lookYaw:Math.PI}]},
 'coat-rack':{rooms:ALL,w:.5,h:.5,z:1.2,cost:75,solids:solid(.5,.5),ports:[]},
 sanitizer:{rooms:ALL,w:.25,h:.25,z:1,cost:60,solids:solid(.25,.25),ports:[]},
 'privacy-screen':{rooms:ALL,w:1.5,h:.25,z:1.15,cost:140,solids:solid(1.5,.25),ports:[]},
 'glass-partition':{rooms:ALL,w:1.5,h:.25,z:1.15,cost:200,solids:solid(1.5,.25),ports:[]},
 'treatment-trolley':{rooms:['gp','pharmacy','therapy','surgery','lab'],w:.75,h:.5,z:.92,cost:220,solids:solid(.75,.5),ports:[{kind:'use',x:.375,y:.75,lookYaw:Math.PI}]},
 'waste-bin':{rooms:ALL,w:.5,h:.5,z:.62,cost:55,solids:solid(.5,.5),ports:[{kind:'use',x:.25,y:.75,lookYaw:Math.PI}]},
 'examination-couch':{rooms:['gp','therapy','surgery'],w:1.75,h:.75,z:.74,cost:320,solids:solid(1.75,.75),ports:[{kind:'use',x:.875,y:1,lookYaw:Math.PI}]}
});
export function satisfiesRequirement(kind,required){return kind===required||!!FURNITURE[kind]?.fulfills?.includes(required);}
export function waitingComfort(room){if(room?.type!=='waiting')return 1;const kinds=new Set((room.furniture||[]).map(item=>item.kind));return 1-Math.min(.15,[...kinds].reduce((sum,kind)=>sum+(FURNITURE[kind]?.comfort||0),0));}
for(const [kind,spec] of Object.entries(FURNITURE)){spec.name={en:OBJECT_INFO[kind][0][0],de:OBJECT_INFO[kind][0][1]};spec.desc={en:OBJECT_INFO[kind][1][0],de:OBJECT_INFO[kind][1][1]};if(spec.ports.some(p=>p.kind==='work'))spec.maxCount=1;}
export function requirements(type){const kinds=type==='reception'?['counter']:['gp','pharmacy','therapy','surgery','lab'].includes(type)?[type]:['waiting','lounge'].includes(type)?['seat']:type==='toilet'?['toilet','sink']:[];return kinds.map(kind=>({kind,need:1}));}
export function rotatedSize(spec,rotation=0){return rotation%2?{w:spec.h,h:spec.w}:{w:spec.w,h:spec.h};}
export function rotateLocal(point,w,h,rotation=0){const {x,y}=point;return rotation===1?{x:h-y,y:x}:rotation===2?{x:w-x,y:h-y}:rotation===3?{x:y,y:w-x}:{x,y};}
export function furniturePoint(r,f,point){const spec=FURNITURE[f.kind],p=rotateLocal(point,spec.w,spec.h,f.rotation);return {x:r.x+f.x+p.x,y:r.y+f.y+p.y};}
export function furnitureRect(r,f,rect){const corners=[{x:rect.x,y:rect.y},{x:rect.x+rect.w,y:rect.y},{x:rect.x,y:rect.y+rect.h},{x:rect.x+rect.w,y:rect.y+rect.h}].map(p=>furniturePoint(r,f,p)),x=Math.min(...corners.map(p=>p.x)),y=Math.min(...corners.map(p=>p.y));return {x,y,w:Math.max(...corners.map(p=>p.x))-x,h:Math.max(...corners.map(p=>p.y))-y};}
export function furniturePorts(r){const out=[];for(const f of r.furniture||[]){const spec=FURNITURE[f.kind];if(!spec)continue;for(const [localIndex,port] of spec.ports.entries()){const world=furniturePoint(r,f,port),approach=port.approach&&furniturePoint(r,f,port.approach);out.push({...port,id:`${r.id}:${f.id}:port-${localIndex}`,furnitureId:f.id,localIndex,x:world.x-.5,y:world.y-.5,lookYaw:(port.lookYaw||0)-f.rotation*Math.PI/2,approach:approach?{x:approach.x-.5,y:approach.y-.5}:null,solidId:port.solidPart?`${f.id}:${port.solidPart}`:null,purpose:port.kind==='seat'?r.type:port.kind});}}return out;}
export function legacyWaitingSeats(r){if(r.type!=='waiting')return [];const out=[],lane=r.x+Math.floor(r.w/2);for(let row=0;row<(r.h>=5?2:1);row++){for(let x=r.x+.3;x<lane-.7;x+=1.05)out.push({x,y:r.y+.45+row*1.8,kind:'chair'});const right=[];for(let x=lane+.85;x<=r.x+r.w-1;x+=.85)right.push(x);for(const x of right.slice(0,2))out.push({x,y:r.y+.45+row*1.8,kind:right.length>=2?'sofa':'chair'});}return out;}
export function waitingSeats(r){if(!Array.isArray(r.furniture))return legacyWaitingSeats(r);return r.type==='waiting'?furniturePorts(r).filter(p=>p.kind==='seat').map((p,index)=>({...p,index})):[];}
export function roomObjects(r){
 const out=[{id:`${r.id}:door`,roomId:r.id,furnitureId:null,kind:'door',x:r.x+Math.floor(r.w/2),y:r.y<8?r.y+r.h-.06:r.y-.06,w:1,h:.12,z:1.12,rotation:0,frame:null,local:null}];
 for(const f of r.furniture||[]){const spec=FURNITURE[f.kind];if(!spec)continue;const parts=spec.parts||[{kind:f.kind,part:'body',x:0,y:0,w:spec.w,h:spec.h,z:spec.z}];for(const part of parts){const frame={x:r.x+f.x,y:r.y+f.y,w:spec.w,h:spec.h,rotation:f.rotation},local={x:part.x,y:part.y,w:part.w,h:part.h};out.push({...part,...furnitureRect(r,f,part),id:`${r.id}:${f.id}:${part.part}`,roomId:r.id,furnitureId:f.id,furnitureKind:f.kind,rotation:f.rotation,frame,local,canonicalW:part.w,canonicalH:part.h,seats:spec.ports.filter(p=>p.kind==='seat').length||undefined});}}
 return out;
}
export function findObject(game,id){for(const r of game.rooms){const object=roomObjects(r).find(o=>o.id===id);if(object)return object;}return null;}
