import {TRAINING,SHIFT_SECONDS,operationStatus,trainingQuote} from './operations.js';

export function renderOperationsPanel(game,{helpers}){
 const {copy,btn,panelHeader}=helpers,status=operationStatus(game),settings=game.operations||{admissionLimit:12,hours:{enabled:false,open:8,close:18}},hours=value=>Array.from({length:24},(_,hour)=>`<option value="${hour}"${value===hour?' selected':''}>${String(hour).padStart(2,'0')}:00</option>`).join('');
 return panelHeader(copy('Clinic operations','Praxisbetrieb'),copy('HOURS & APPOINTMENTS','ZEITEN & TERMINE'))+`<div class="panel-scroll operations-content"><p class="panel-intro">${copy('Choose your opening window and how many people to admit. Existing appointments always finish.','Lege Öffnungszeiten und Aufnahmegrenze fest. Bereits aufgenommene Patienten werden weiter versorgt.')}</p><div class="operations-status"><b>${!game.admissionsOpen?copy('Clinic not opened yet','Praxis noch nicht eröffnet'):status.open?copy('Within opening hours','Innerhalb der Öffnungszeiten'):copy('Admissions closed for this shift','Aufnahme in dieser Schicht geschlossen')}</b><span>${copy('Shift clock','Betriebsuhr')}: ${String(Math.floor(status.hour)).padStart(2,'0')}:${String(Math.floor(status.hour%1*60)).padStart(2,'0')}</span></div><label class="operations-field" for="operations-limit">${copy('Maximum patients in care','Höchstens gleichzeitig in Behandlung')}<select id="operations-limit">${Array.from({length:12},(_,i)=>`<option value="${i+1}"${settings.admissionLimit===i+1?' selected':''}>${i+1}</option>`).join('')}</select></label><p class="development-note">${copy('This is an upper bound. The clinic still admits fewer people when staffing, treatment capacity or queues require it. Lowering the limit never sends existing patients away.','Dies ist eine Obergrenze. Personal, Behandlungskapazität und Warteschlangen können die Aufnahme weiter begrenzen. Eine niedrigere Grenze schickt niemanden nach Hause.')}</p><label class="operations-toggle"><input type="checkbox" id="operations-scheduled"${settings.hours.enabled?' checked':''}> ${copy('Use scheduled opening hours','Feste Öffnungszeiten verwenden')}</label><div class="operations-hours"><label for="operations-open">${copy('Open from','Geöffnet ab')}<select id="operations-open">${hours(settings.hours.open)}</select></label><label for="operations-close">${copy('Close at','Geschlossen ab')}<select id="operations-close">${hours(settings.hours.close)}</select></label></div><p class="development-note">${copy(`The shift clock repeats every ${SHIFT_SECONDS} simulation seconds and runs separately from financial months. Overnight hours are possible. With scheduling off, admissions stay open around the clock.`,`Die Betriebsuhr wiederholt sich alle ${SHIFT_SECONDS} Spielsekunden und läuft unabhängig von Finanzmonaten. Nachtschichten sind möglich. Ohne Zeitplan ist die Aufnahme rund um die Uhr offen.`)}</p><p class="development-note">${copy('Outside opening hours, staff finish appointments and training continues. Salaries and upkeep still apply.','Außerhalb der Öffnungszeiten werden Termine beendet und Fortbildungen fortgesetzt. Gehälter und Unterhalt laufen weiter.')}</p>${btn('operations-apply',copy('Apply operations settings','Betriebseinstellungen übernehmen'),'primary full')}</div>`;
}

export function renderStaffTraining(game,staff,helpers){
 const {copy,label,escape,btn,money}=helpers,course=staff.trainingCourse,levels=staff.training||{},sum=Object.values(levels).reduce((a,b)=>a+b,0),maximum=Object.values(TRAINING).filter(spec=>spec.roles.includes(staff.role)).length*2;
 if(course){const spec=TRAINING[course.track],duration=spec.duration+(course.level-1)*15,off=staff.state==='break'||staff.awaitingPlacement;return `<section class="staff-training active"><b>${escape(label(spec.name))} · ${copy('Level','Stufe')} ${course.level}</b><p>${off?copy('Studying during a break','Lernt in einer Pause'):copy('Finishes the current task, then goes to training','Beendet den aktuellen Auftrag und geht dann zur Fortbildung')}</p><progress max="${duration}" value="${course.progress}" aria-label="${escape(copy('Training progress','Fortbildungsfortschritt'))}"></progress><small>${Math.ceil(duration-course.progress)} ${copy('simulation seconds remaining','Spielsekunden verbleibend')}</small></section>`;}
 return `<details class="staff-training" data-training-staff="${staff.id}"><summary>${copy('Paid training','Bezahlte Fortbildung')}${sum?' · '+sum+'/'+maximum:''}</summary><p>${copy('Up to two levels per course. The employee finishes their current task, then studies during a break.','Bis zu zwei Stufen je Kurs. Die Person beendet ihren aktuellen Auftrag und lernt anschließend in einer Pause.')}</p>${Object.entries(TRAINING).filter(([,spec])=>spec.roles.includes(staff.role)).map(([track,spec])=>{const quote=trainingQuote(game,staff.id,track),level=levels[track]||0;return `<article class="training-option"><b>${escape(label(spec.name))} · ${level}/2</b><p>${escape(label(spec.desc))}</p>${level>=2?`<small>✓ ${copy('Fully trained','Vollständig geschult')}</small>`:btn('staff-train',`${copy('Level','Stufe')} ${level+1} · ${money(quote.cost)} · ${quote.duration}s`,'secondary full',`data-id="${staff.id}" data-track="${track}" ${quote.error?'disabled':''}`)}</article>`;}).join('')}${!game.admissionsOpen?`<p>${copy('Training begins after the clinic has opened.','Fortbildungen beginnen nach der Praxiseröffnung.')}</p>`:''}</details>`;
}
