import {MAX_SAVE_SLOTS} from './save-library.js';

export function renderSaveLibrary(game,{mode='load',slots=[],latest=null,libraryError=null,startScreen=false,helpers}){
 const {copy,t,btn,money,escape,lang}=helpers;
 const modeName=g=>t(g.mode==='tutorial'?'tutorial':g.mode==='sandbox'?'sandbox':'campaign');
 const detail=g=>`${modeName(g)} · ${t('year')} ${g.year||1} · ${t('month')} ${g.month||1} · ${money(Number.isFinite(g.cash)?g.cash:0)}`;
 const date=value=>new Intl.DateTimeFormat(lang,{dateStyle:'short',timeStyle:'short'}).format(new Date(value));
 return `<div class="modal-body save-library"><span class="eyebrow">FUNNY HOSPITAL · ${slots.length} / ${MAX_SAVE_SLOTS}</span><h2>${copy(mode==='save'?'Save your clinic':'Load a clinic',mode==='save'?'Klinik speichern':'Klinik laden')}</h2><p class="modal-subtitle">${copy('Keep several named clinics in this browser. Export a JSON file for another device or a backup.','Bewahre mehrere benannte Kliniken in diesem Browser auf. Für ein anderes Gerät oder eine Sicherung exportierst du eine JSON-Datei.')}</p>${mode==='save'&&!startScreen?`<div class="save-create"><label for="save-slot-name">${copy('Name of this save','Name des Spielstands')}</label><div><input id="save-slot-name" maxlength="48" value="${escape(copy('My clinic','Meine Klinik'))}" autocomplete="off"/><button class="primary" data-action="slot-create" ${libraryError||slots.length>=MAX_SAVE_SLOTS?'disabled':''}>${copy('Save new','Neu speichern')}</button></div>${slots.length>=MAX_SAVE_SLOTS?`<small>${copy('All slots are full. Replace or remove an existing named save.','Alle Plätze sind belegt. Ersetze oder entferne einen benannten Spielstand.')}</small>`:''}</div>`:''}${libraryError?`<p class="editor-warning">${escape(libraryError)}</p>`:''}<section class="latest-save"><div><b>${copy('Latest quick save / autosave','Letzter Schnell- / Autosave')}</b><small>${latest?escape(detail(latest)):copy('No readable quick save yet','Noch kein lesbarer Schnellspielstand')}</small></div>${mode==='save'&&!startScreen?btn('quick-save',copy('Quick save','Schnellspeichern'),'secondary'):btn('load-latest',copy('Load','Laden'),'secondary',latest?'':'disabled')}</section><div class="named-saves">${slots.map(slot=>`<article class="save-slot"><div class="save-slot-heading"><h3>${escape(slot.name)}</h3><time>${date(slot.updatedAt)}</time></div><p>${escape(detail(slot.snapshot))}</p><div class="save-slot-actions">${btn('slot-load',copy('Load','Laden'),'secondary',`data-slot="${escape(slot.id)}"`)}${mode==='save'&&!startScreen?btn('slot-overwrite',copy('Replace','Ersetzen'),'secondary',`data-slot="${escape(slot.id)}"`):''}${btn('slot-rename',copy('Rename','Umbenennen'),'text-button',`data-slot="${escape(slot.id)}"`)}${btn('slot-export',copy('Export','Exportieren'),'text-button',`data-slot="${escape(slot.id)}"`)}${btn('slot-delete',copy('Remove','Entfernen'),'text-button danger',`data-slot="${escape(slot.id)}"`)}</div></article>`).join('')||(!libraryError?`<p class="empty-save-library">${copy('No named saves yet. Your quick save is kept separately.','Noch keine benannten Spielstände. Dein Schnellspielstand bleibt separat erhalten.')}</p>`:'')}</div><div class="save-library-footer">${btn('import','↑ '+t('import'),'secondary')}${btn('export','↓ '+t('export'),'secondary')}${btn('close-modal',t('close'),'text-button')}</div></div>`;
}
