export const MONTH_SECONDS=30;
export const YEAR_SECONDS=12*MONTH_SECONDS;
export const ANNUAL_TARGET=100000;
export const GUIDE=[
 {id:'reception',room:'reception',rect:{x:15,y:12,w:5,h:4},title:{en:'Start with a proper welcome',de:'Alles beginnt am Empfang'},text:{en:'Build reception on the marked floor. Every patient must check in here before seeing a doctor.',de:'Baue die Rezeption auf der markierten Fläche. Hier meldet sich jeder Patient vor dem Arztbesuch an.'}},
 {id:'receptionist',cast:'rosa',title:{en:'Give reception a real person',de:'Besetze die Rezeption'},text:{en:'Hire Rosa Reed. An empty desk cannot register patients. Rosa automatically takes the reception desk.',de:'Stelle Rosa Reed ein. Ein leerer Tresen nimmt niemanden auf. Rosa übernimmt automatisch die Rezeption.'}},
 {id:'diagnosis',room:'gp',rect:{x:2,y:2,w:5,h:4},title:{en:'Build your first diagnosis room',de:'Baue deine erste Diagnostik'},text:{en:'Place a diagnosis room in the highlighted area. Keep its door connected to the entrance.',de:'Platziere die Diagnostik auf der markierten Fläche. Die Tür braucht einen freien Weg zum Eingang.'}},
 {id:'doctor',cast:'milo',title:{en:'The doctor will see you now',de:'Ein Arzt für deine Klinik'},text:{en:'Hire Dr. Milo Finch. He will diagnose the curious cases that Rosa checks in.',de:'Stelle Dr. Milo Finch ein. Er untersucht die kuriosen Fälle, die Rosa aufnimmt.'}},
 {id:'pharmacy',room:'pharmacy',rect:{x:8,y:2,w:5,h:4},title:{en:'Diagnosis needs a happy ending',de:'Diagnosen brauchen eine Behandlung'},text:{en:'Build a pharmacy. It treats the espresso tremolo and inbox inflammation arriving in this tutorial.',de:'Baue eine Apotheke. Sie behandelt Espresso-Tremolo und Postfachentzündung in diesem Tutorial.'}},
 {id:'nurse',cast:'bea',title:{en:'Hire the actual boss',de:'Stelle die eigentliche Chefin ein'},text:{en:'Hire Bea Bell to run the pharmacy. Doctors cannot cover a nurse’s position.',de:'Stelle Bea Bell für die Apotheke ein. Ärzte können keine Pflegestelle übernehmen.'}},
 {id:'open',title:{en:'Open the doors',de:'Öffne die Klinik'},text:{en:'Your core team is ready. Open the clinic to start admissions and the financial calendar. One month lasts 30 seconds, one year six minutes at 1×.',de:'Dein Kernteam steht. Öffne die Klinik: Patienten und Finanzkalender starten. Ein Monat dauert 30 Sekunden, ein Jahr sechs Minuten bei 1×.'}},
 {id:'firstArrival',title:{en:'Your first patient is on the way',de:'Dein erster Patient kommt'},text:{en:'Watch the entrance. Rosa checks each person in before sending them to diagnosis.',de:'Achte auf den Eingang. Rosa nimmt jede Person auf und schickt sie danach zur Diagnostik.'}},
 {id:'chart',title:{en:'A person, not just a queue',de:'Ein Mensch, nicht nur eine Schlange'},text:{en:'Open Patients and select a name, or click a character. Read their personal chart, complaint, bill and care timeline.',de:'Öffne Patienten und wähle einen Namen oder klicke eine Figur an. Schau dir Stammblatt, Beschwerden, Rechnung und Behandlungsverlauf an.'}},
 {id:'cures',title:{en:'Follow three happy endings',de:'Drei gute Ausgänge'},text:{en:'Cure three patients. Follow registration → diagnosis → pharmacy. Empty or unstaffed rooms stop the chain.',de:'Heile drei Patienten. Beobachte Aufnahme → Diagnostik → Apotheke. Fehlende Räume oder unbesetzte Stellen unterbrechen den Ablauf.'}},
 {id:'lounge',room:'lounge',rect:{x:17,y:2,w:5,h:4},title:{en:'Coffee breaks are infrastructure',de:'Pausen gehören zur Infrastruktur'},text:{en:'Build a staff lounge. Tired people need a proper break to keep treating patients reliably.',de:'Baue einen Pausenraum. Erschöpfte Mitarbeiter brauchen Erholung, damit die Behandlung weiterläuft.'}},
 {id:'toilet',room:'toilet',rect:{x:2,y:11,w:3,h:3},title:{en:'A little comfort goes a long way',de:'Ein bisschen Komfort hilft'},text:{en:'Build restrooms. Comfortable patients stay patient for longer.',de:'Baue Toiletten. Zufriedene Patienten bleiben länger geduldig.'}},
 {id:'janitor',cast:'otto',title:{en:'Keep it clean, keep it running',de:'Sauber halten, Betrieb sichern'},text:{en:'Hire Otto Sparks for cleaning and maintenance. Dirty rooms reduce treatment success.',de:'Stelle Otto Sparks für Reinigung und Wartung ein. Schmutzige Räume senken den Behandlungserfolg.'}},
 {id:'upgradeGp',upgrade:'gp',title:{en:'Less waiting, more care',de:'Weniger warten, mehr behandeln'},text:{en:'Upgrade the diagnosis room to level 2. The doctor can now handle cases faster.',de:'Verbessere die Diagnostik auf Stufe 2. So kann der Arzt Fälle schneller bearbeiten.'}},
 {id:'upgradePharmacy',upgrade:'pharmacy',title:{en:'Make room for recovery',de:'Mehr Kapazität für Heilung'},text:{en:'Upgrade the pharmacy to level 2. Better equipment speeds treatment and improves its success rate.',de:'Verbessere die Apotheke auf Stufe 2. Bessere Geräte beschleunigen die Behandlung und erhöhen die Erfolgschance.'}},
 {id:'profit',title:{en:'Your first $100,000 year',de:'Dein erstes 100.000-Dollar-Jahr'},text:{en:'Reach $100,000 actual profit when the year closes. Starting capital does not count; construction, hiring, research, supplies and monthly bills are all deducted. Use 3× to speed up. If you miss the target, try the next year.',de:'Erreiche beim Jahresabschluss 100.000 $ tatsächlichen Gewinn. Startkapital zählt nicht; Bau, Einstellungen, Forschung, Material und Monatsrechnungen werden abgezogen. Mit 3× geht es schneller. Falls es nicht reicht, versuche es im nächsten Jahr.'}}
];
export function guideIndex(g){
 const has=t=>g.rooms.some(r=>r.type===t),staffed=t=>g.rooms.some(r=>r.type===t&&r.staffId),up=t=>g.rooms.some(r=>r.type===t&&r.level>=2);
 const done=[has('reception'),staffed('reception'),has('gp'),staffed('gp'),has('pharmacy'),staffed('pharmacy'),g.admissionsOpen,g.records.length>0,g.tutorial.chartRead,g.cured>=3,has('lounge'),has('toilet'),g.staff.some(s=>s.role==='janitor'),up('gp'),up('pharmacy'),g.won];
 return Math.max(0,done.findIndex(v=>!v));
}
